### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [libproxy/libproxy#100]
It already +2y since last release.
I think that it would be good to flush away already committed changes and make new release :)

**Comment by smcv** [comment]
See also #81, #82 which might be blockers for a new release.

**Comment by mcatanzaro** [comment]
#81 is not a regression though, it's a longstanding bug. Would definitely be nice to fix, of course.

#82 would be a pretty serious regression if not fixed.

**Comment by smcv** [comment]
#82 is now fixed.

#81 isn't, but it also isn't a regression, so as you say it doesn't need to block a new release.

**Comment by mcatanzaro** [comment]
#81 is pretty well-mitigated, though. Will leave a comment there.

**Comment by DimStar77** [comment]
0.4.16 has been published - 0.4.17 will follow by end of the year (python bindings in 0.4.16 are broken - fixed in git)

**Comment by kloczek** [comment]
Thank you :)
