### ISSUE TITLE
Boost Software License?

### ISSUE THREAD

**Issue by vinniefalco** [libproxy/libproxy#103]
LGPL is way too restrictive, is there any chance this could be re-released under the Boost Software License? Thanks!

**Comment by DimStar77** [comment]
@ndufresne @npmccallum - you two are the main authors and without your buy-in, there is no need to even approach the contributors of smaller patchsets

**Comment by npmccallum** [comment]
What is the need for this?

**Comment by ndufresne** [comment]
Would need a better rationale then "it's too restrictive" to get my buy in. I'm open to let my (small) contribution be relicensed, but I need a convincing argument. There is millions of projects in the world that link against LGPL licences software and make good business out of it. Why is it suddenly too restrictive ? And why Boost ?

**Comment by vinniefalco** [comment]
Quite simply, LGPL code cannot be copied and pasted to Boost library source code. MIT license isn't good enough either (since it is ambiguous on whether binaries must carry copyright notice attributions).

I want to include source code from this library into a new library I am writing, which I am going to propose for Boost. But I cannot do that under the current license.

**Comment by ndufresne** [comment]
Copy-pasting is not the intent of this project, that is not from my perspective a good reason. The intent was that there would be a single library, hence a single place to fix issues. I'm not saying it worked out, but that is how I see it. Now feel free to check the authors (git blame) on the files that contains the code you'd like to copy, their author are free to do what they want.
