### ISSUE TITLE
Cross-compilation of libproxy for linux-arm

### ISSUE THREAD

**Issue by jimson-msft** [libproxy/libproxy#120]
Hi, I'm looking to cross-compile libproxy on arm. I see that arm packages for libproxy were generated here: https://archlinuxarm.org/packages/arm/libproxy

Using arm-linux-gnueabihf, is there support/instructions somewhere detailing how to cross-compile to arm?

Currently trying to compile by setting the cmake compiler to the above cross-compiler and hitting this link error:
Scanning dependencies of target symbollnk
[ 56%] Building CXX object libmodman/test/CMakeFiles/symbollnk.dir/main.cpp.o
[ 57%] Linking CXX executable symbollnk
/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [libmodman/test/symbollnk] Error 1
libmodman/test/CMakeFiles/symbollnk.dir/build.make:85: recipe for target 'libmodman/test/symbollnk' failed
make[1]: *** [libmodman/test/CMakeFiles/symbollnk.dir/all] Error 2
CMakeFiles/Makefile2:1589: recipe for target 'libmodman/test/CMakeFiles/symbollnk.dir/all' failed
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

All help appreciated

**Comment by Vogtinator** [comment]
Looks like you're on the right way, but building the modman tests requires zlib.
You either have to install zlib or pass `-DBUILD_TESTING=OFF` to `cmake` to disable tests.

**Comment by jimson-msft** [comment]
Thanks Vogtinator! The -DBUILD_TESTING=OFF flag is able to finish building libproxy. Much appreciated!
