### ISSUE TITLE
Windows build using mingw, 'strdup' issues

### ISSUE THREAD

**Issue by evanrinehart** [libproxy/libproxy#124]
I'm building this to get headers in order to build something with libproxy as dependency on windows. The latest release and the lastest master fail to build due to missing `strdup`. 

```
libproxy/proxy.cpp:475:15: error: ‘strdup’ was not declared in this scope; did you mean ‘strcmp’?
  475 |   retval[i] = strdup(proxies[i].c_str());
      |               ^~~~~~
      |               strcmp
```

This is with the latest gcc package from msys2's pacman. The comment earlier in the file

```#include <cstring> // For strdup()```

seems to indicate there was a problem with this before. The compiler settings used here must cause strdup to be unavailable.

gcc version 9.3.0

**Comment by janbrummer** [comment]
Closing as obsolete.
