### ISSUE TITLE
url::get_pac does not follow redirects

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#135]
url::get_pac does not follow redirects. It just gives up if the response status code is not 200. I was debugging why a test URL that I had hosted on people.gnome.org was not working; it was because people.gnome.org was redirecting from http:// (the only URLs that glib-networking allows to be used for proxy-autoconfig) to https:// and so was returning status code 302.

**Comment by mcatanzaro** [comment]
(Of course, I wouldn't expect it to *work*, since libproxy doesn't support https://, but it should probably be able to follow a simple redirect?)

**Comment by DimStar77** [comment]
following a 3xx redirect is indeed something that should happen, that was even clearly stated in the draft (which was never really ratified - but hey); https though was never mentioned (and I'm not sure if it makes that much sense)

```
4.6. Retrieving the CFILE at the CURL
   The client then requests the CURL via HTTP.
    …
   The client MUST follow HTTP redirect directives (response codes 3xx)
   returned by the server. The client SHOULD send a valid "User-Agent"
   header.
```

**Comment by mcatanzaro** [comment]
> The client SHOULD send a valid "User-Agent" header.

libproxy isn't doing that either.

**Comment by mcatanzaro** [comment]
In [this issue](https://gitlab.gnome.org/GNOME/epiphany/-/issues/1566), a PAC that works properly in Firefox fails because of this redirect problem. And unfortunately it's a redirect to HTTPS.

I spent quite a while debugging this because libproxy does not provide any error message. Since libproxy does not propagate error messages up to the caller, it ought to at least print a warning. There is some debug currently, but it does not print by default.

**Comment by janbrummer** [comment]
Closing as obsolete.
