### ISSUE TITLE
RFE: port to mozjs-78

### ISSUE THREAD

**Issue by kloczek** [libproxy/libproxy#138]
As tit is in subject :)

**Comment by mkszuba** [comment]
Any news on this? BTW. It is more than likely that I have missed something but at least on my own system, all I had to do to make libproxy-0.4.17 build, test and install against mozjs-78 without any problems was change "mozjs-68" to "mozjs-78" in `libproxy/cmake/modules/pacrunner_mozjs.cmk`.

**Comment by lostnet** [comment]
Can this be closed out? mozjs-78 has not received updates since it was EOL about 6 months ago. The target could be changed to mozjs-91 which has about 4 months of support left.

**Comment by kloczek** [comment]
Yes it can be because it has been done.

**Comment by kloczek** [comment]
BTW lates 0.4.17 looks like still is looking for even older version
```console
-- Checking for one of the modules 'mozjs-68'
```
