### ISSUE TITLE
Never use system libmodman

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#140]
Turns out libmodman is a system library. The only upstream source repo is libproxy, which does not install libmodman systemwide, but distros build the system package using a 10-year-old tarball from Google Code. So libproxy internals are amazingly public API/ABI, which complicates improving them.

Since libproxy itself doesn't install libmodman, all we need to do to make changes safely is to stop using the system version and always use our bundled libmodman. libproxy is the only software using libmodman, so distros can then retire their libmodman packages.

**Comment by smcv** [comment]
For what it's worth, the Debian family of distributions already uses the bundled copy (I don't think we ever had a separate libmodman package).

**Comment by mcatanzaro** [comment]
> For what it's worth, the Debian family of distributions already uses the bundled copy (I don't think we ever had a separate libmodman package).

Good!
