### ISSUE TITLE
libproxy is not exception-safe

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#141]
libproxy exceptions but none of the code is exception-safe. libproxy uses naked new/delete all over the place, which is unsafe when code can throw exceptions. So that all needs to be converted to use std::unique_ptr to be safe.

I actually started on this as an experiment, but got distracted when I discovered that my changes to libmodman were not taking effect, #140.

**Comment by janbrummer** [comment]
Closing as obsolete.
