### ISSUE TITLE
Please upload release tarballs

### ISSUE THREAD

**Issue by vincele** [libproxy/libproxy#150]
Same as issue #73 but for the latest release 0.4.16.

Maybe add some check so that the release process is enforced.

**Comment by DimStar77** [comment]
Thanks for the reminder; I really should stick better to the release script I have :)

tar.xz attached tot he release (note: 0.4.17 will come soon to address the python regression in 0.4.16)

**Comment by vincele** [comment]
Thanks for the update to 0.4.17 and the tarball.
This has been submitted for update in GNU Guix.
