### ISSUE TITLE
pacrunner_mozjs module disabled even with -DWITH_MOZJS=ON

### ISSUE THREAD

**Issue by Arfrever** [libproxy/libproxy#153]
In commit 2203f710988eaa3061e75b083296944e34e17d59:
```
--- a/libproxy/cmake/modules.cmk
+++ b/libproxy/cmake/modules.cmk
@@ -44,7 +44,7 @@ if(NM_FOUND OR NMold_FOUND)
   set(NM_BUILD 1)
 endif(NM_FOUND OR NMold_FOUND)
 px_module(network_networkmanager   "${NM_BUILD}"     0       ${NM_LIBRARIES}${NMold_LIBRARIES})
-px_module(pacrunner_mozjs          "${MOZJS_FOUND}"  ${BIPR} ${MOZJS_LIBRARIES})
+px_module(pacrunner_mozjs          0                 ${BIPR} ${MOZJS_LIBRARIES})
 px_module(pacrunner_natus          "${NATUS_FOUND}"  ${BIPR} ${NATUS_LIBRARIES})
 px_module(pacrunner_webkit         "${WEBKIT_FOUND}" ${BIPR} ${WEBKIT_LIBRARIES})
 px_module(wpad_dns_alias           1                 1)
```
This change results in disabling `pacrunner_mozjs` module even when libproxy is configured with `-DWITH_MOZJS=ON`.

In order to disable it by default, but to allow to enable it for those users who want it, `option(WITH_MOZJS "Search for MOZJS package" ON)` should have been changed instead.

Patch: [libproxy-pacrunner_mozjs.patch.txt](https://github.com/libproxy/libproxy/files/5758407/libproxy-pacrunner_mozjs.patch.txt)

**Comment by DimStar77** [comment]
That was actually pretty intentional, to raise the bar to enable mozjs pacrunner a bit higher;

mozjs pacrunner is amongst the most frequent cases for crashes, especially with GNOME apps

Version 0.5 of libproxy is supposedly moving to dbus, taking all the pacrunners out of the application memory, making things much smoother. But until then, we basically simply discourage mozjs pacrunner

**Comment by mcatanzaro** [comment]
> In order to disable it by default, but to allow to enable it for those users who want it, option(WITH_MOZJS "Search for MOZJS package" ON) should have been changed instead.

I think that's probably what I *meant* to do, oops. :)

Of course, the WebKit backend is likely to result in similar crashes in the future if applications link to an incompatible version of WebKit, for example.

I received a suggestion that libproxy should use an embedded JS engine like duktape or quickjs or similar. That would work without the requirement to dbusify.
