### ISSUE TITLE
there is only direct://

### ISSUE THREAD

**Issue by peguine** [libproxy/libproxy#164]
PS D:\doc\c++\libproxy-0.4.17\cmake-build-debug\libproxy> .\proxy.exe https://www.google.com
direct://
PS D:\doc\c++\libproxy-0.4.17\cmake-build-debug\libproxy> .\proxy.exe https://www.youtube.com
direct://
PS D:\doc\c++\libproxy-0.4.17\cmake-build-debug\libproxy> .\proxy.exe https://www.youtube.com
direct://
PS D:\doc\c++\libproxy-0.4.17\cmake-build-debug\libproxy> .\proxy.exe http://www.google.com
direct://

why

**Comment by peguine** [comment]
I tried both on windows 10 and macos ,could not  get the proxy list at all.

**Comment by janbrummer** [comment]
Closing as obsolete.
