### ISSUE TITLE
config_gnome and config_gnome3 modules leave an unnecessary shell running

### ISSUE THREAD

**Issue by phodd** [libproxy/libproxy#168]
Both config_gnome.cpp and config_gnome3.cpp have `popen2()` functions that, under some circumstances, use `sh -c` to start another process.

While `popen2()` `execl`s the shell, causing the child process to exit, the shell itself does not `exec` its argument, meaning it only exits when its own child exits. Since the shell apparently has no clean-up to do, this seems like a wasteful extra process.

I am unsure if simply inserting the `"exec"` shell keyword into to the shell command just before the `program` parameter will have the desired effect.

I am also unsure if the shell is even necessary, since whatever the shell is calling is itself a program, and whatever that is might work as the first parameter(s) of the `execl` call.

Something that works when called with a shell but not without usually has some kind of environment problem.

**Comment by janbrummer** [comment]
Closing as obsolete.
