### ISSUE TITLE
"redirected you too many times" in Brave/Chromium and clearing cookies

### ISSUE THREAD

**Issue by danielsgriffin** [libproxy/libproxy#170]
Hi,

I'm not sure where this issue originates (on the publisher's website side, my campus libraries' implementation via EZproxy, or my configuration) but I frequently get this failure while loading libproxy.berkeley.edu pages. The Brave/Chromium error message says something like:

> This page isn’t working
> dl-acm-org.libproxy.berkeley.edu redirected you too many times.
> Try clearing your cookies.
> 
> ERR_TOO_MANY_REDIRECTS

Following the 'Try clearing your cookies.' link from the message goes to https://support.google.com/chrome/answer/95647 with generic information about clearing cookies. I've not wanting to clear all cookies so would always just re-load the page in incognito and re-login to my campus.

After closer inspection, the specific cookies that need clearing (at least in this last instance for me) seem to be the cookies from the original publisher. So since the redirect message was re 'dl-acm-org.libproxy.berkeley.edu' then I searched (in my case at the top right of brave://settings/siteData) for cookies matching [acm.org] and removed them all. The page then immediately loaded fully.

I'm writing this in case someone else runs into a similar problem and searches for a resolution. I'm also wondering if I should just contact my campus library directly.

My campus currently only has this guidance regarding cookies:

https://guides.lib.berkeley.edu/ezproxy/faq

> Q. I got a Cookie Error. What do I do?
> 
> A. Both EZproxy and certain databases send "cookies" when you connect to them to verify, during your session, that you are an authorized user. If your browser reports an error receiving a "cookie," it may be currently set to disallow cookies. Make sure that your browser allows third party cookies.

That doesn't seem to be the issue here. Is there something I should encourage them to include?

Thank you.

**Comment by mcatanzaro** [comment]
Huh, it looks like somebody decided to make a proxy service for physical book libraries and name libproxy, and that's what you're having trouble with. That's... pretty braindead. Wow.

This is the issue tracker for the libproxy software library that's installed on basically every Linux or BSD computer. You'd think Berkeley might have known better, especially considering where BSD comes from, but whatever. I look forward to watching the confusion play out....

**Comment by mcatanzaro** [comment]
Hi @DimStar77, you can close this!

**Comment by DimStar77** [comment]
> Hi @DimStar77, you can close this!

Thanks.... You should be maintainer here too 😏

**Comment by mcatanzaro** [comment]
God forbid.
