### ISSUE TITLE
[RFC] Prioritise environment variable if they exist

### ISSUE THREAD

**Issue by SuibianP** [libproxy/libproxy#174]
Currently, there is no way for one to override a proxy from environment variables, which is by design:

https://github.com/libproxy/libproxy/blob/1d8f02ebfb93d388dbf82c16a0d6c3293681a0eb/libproxy/modules/config_envvar.cpp#L68-L71

However, this can be inconvenient for just temporarily overriding/bypassing a proxy without reaching for some far fetched setting at GNOME/KDE etc.

It would be better for the `envvar_config` module to have top priority if the environment variables exist and simply fail the test otherwise. In other words, environment variables should always be respected if they exist.

**Comment by DimStar77** [comment]
The problem is that most distro/desktops export some nonsense HTTP_PROXY envvar out to the terminals in an attempt 'to help the user'; so putting envvar to top prior invalidates most of the other plugins on most distros

**Comment by SuibianP** [comment]
Thanks for pointing this out! Admittedly this is new to me, as it does not happen on my configuration (stock GNOME on Wayland from openSUSE Tumbleweed).

```
hujialun@bogon:~> printenv | grep -i proxy
hujialun@bogon:~> gsettings get org.gnome.system.proxy autoconfig-url
'http://127.0.0.1:9809/proxy.pac'
hujialun@bogon:~> gsettings get org.gnome.system.proxy mode
'auto'
hujialun@bogon:~> printenv | grep -i session
SESSION_MANAGER=local/bogon:@/tmp/.ICE-unix/2576,unix/bogon:/tmp/.ICE-unix/2576
DESKTOP_SESSION=gnome-wayland
XDG_SESSION_DESKTOP=gnome-wayland
XDG_SESSION_TYPE=wayland
XDG_SESSION_CLASS=user
GDMSESSION=gnome-wayland
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

A quick googling does not give me any useful hints. Could you please point me to some links about the nonsense values?

**Comment by DimStar77** [comment]
IIRC on Tumbleweed, if you set 'static' HTTP proxies in GNOME (not wpad/pac and the like) they are exported to env when you start gnome-terminal

**Comment by SuibianP** [comment]
Yes, but it should not pose a problem as those manual proxies would be what libproxy is obtaining in the end anyway :thinking:

Alternatively, it might be possible to invent our own "master override" environment variables, or allow individual modules to be disabled via environment variables for libmodman. I am not sure if such new environment variables would be desirable, though.

**Comment by DimStar77** [comment]
> Yes, but it should not pose a problem as those manual proxies would be what libproxy is obtaining in the end anyway thinking

except if you already have a terminal open and change the proxy settings in ghte gnome settings. As it is now, the setting just applied to g-c-c win. if envvar is prioritized, then only newly launched terminals will be correct. This is not wanted

**Comment by DimStar77** [comment]
> Alternatively, it might be possible to invent our own "master override" environment variables, or allow individual modules to be disabled via environment variables for libmodman. I am not sure if such new environment variables would be desirable, though.

very early versions of libproxy allowed to override the order of the modules loading - but this was quite fragile and a constant cause of trouble

**Comment by SuibianP** [comment]
On another thought, I think what we actually need is just a mechanism to behave just according to the environment variable conventions. Maybe a master switch to just use the good old environment variables, something like `PX_PROXY_ENV_ONLY`?

**Comment by DimStar77** [comment]
> On another thought, I think what we actually need is just a mechanism to behave just according to the environment variable conventions. Maybe a master switch to just use the good old environment variables, something like `PX_PROXY_ENV_ONLY`?

That would actually be quite simple to implement - i.e. have the various config_modules return FALSE if that env is set (we could even do PX_PROXY_FORCE_CONFIG={env,gnome3,kde} and return FALSE if set and not the current config module being loaded)

@Vogtinator WDYT? This could be beneficial also for some debugging

**Comment by bigon** [comment]
Hello,

For the record, libproxy is used by libsoup and libsoup can be used by daemon as well

Concrete case, geoclue uses libsoup and with libproxy not using the environment variables, it's not possible to set a proxy for the geolocation requests. 

Note that geoclue is stared as a system service under its own user. That means that there is no user session opened (no gconf/dconf/...)

Shouldn't the module allowed to fail to load if there is no gconf or if it's running outside of a desktop environment and fallback to the environment variables ? 

An other option would be to have libsoup have an option to bypass libproxy and get the proxy from the environment I guess.
