### ISSUE TITLE
libproxy not using wpad host

### ISSUE THREAD

**Issue by elshyam** [libproxy/libproxy#177]
I have wpad host entry in `/etc/hosts` 
but `proxy` command just returns `direct://`
Shouldn't it resolve the `wpad` hostname and get `wpad.dat` file and
return appropriate proxy

**Comment by DimStar77** [comment]
What config module are you using?

The configuration must be pointing at 'automatic configuration for proxies', other wise the wpad entry itself does not do anything

in my case for example I get:

```
> _PX_DEBUG=1 proxy https://www.google.com
Configuration extension is: 22gnome_config_extension
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
Ignored list is: localhost,127.0.0.0/8,::1,*suse.com
Config is: 
direct://
```

so I'd need to configure automatic proxy config in gnome-control-center, Network, Network Proxy, automatic
