### ISSUE TITLE
perl: test suite failure on i586

### ISSUE THREAD

**Issue by DimStar77** [libproxy/libproxy#182]
```
> ctest --rerun-failed --output-on-failure
Test project /home/abuild/rpmbuild/BUILD/libproxy-0.4.18/build
    Start 8: perl
1/1 Test #8: perl .............................***Failed    0.21 sec
/home/abuild/rpmbuild/BUILD/libproxy-0.4.18/bindings/perl/src/Libproxy.c: loadable library and perl binaries are mismatched (got handshake key 0x8d40080, needed 0x8dc0080)
/home/abuild/rpmbuild/BUILD/libproxy-0.4.18/bindings/perl/t/Libproxy.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
/home/abuild/rpmbuild/BUILD/libproxy-0.4.18/bindings/perl/t/Libproxy.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  0 wallclock secs ( 0.04 usr  0.00 sys +  0.06 cusr  0.00 csys =  0.10 CPU)
Result: FAIL


0% tests passed, 1 tests failed out of 1

```

on x86_64, the test suite passes

**Comment by Vogtinator** [comment]
That looks strange. It's not cross compiling in any way, right?

**Comment by DimStar77** [comment]
> That looks strange. It's not cross compiling in any way, right?

https://build.opensuse.org/package/live_build_log/GNOME:Next/libproxy:plugins/openSUSE_Factory/i586

lazily using OBS

**Comment by Vogtinator** [comment]
It's about missing `-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64` (mostly the latter), so the size of some types is different, which causes a struct size sanity check to fail. Question is how to get to those flags.

**Comment by DimStar77** [comment]
can we inject

`perl -V:ccflags` output there?

**Comment by Vogtinator** [comment]
That's also the only option I see, as not even `PERL_EXTRA_C_FLAGS` has the necessary content...

I also prefer the latter, that doesn't need unquoting at least. I'll try that.
