### ISSUE TITLE
Consider using more permissive license

### ISSUE THREAD

**Issue by nmoinvaz** [libproxy/libproxy#186]
I am wondering if you would consider using a more permissive license such as MIT or BSD. We have unique requirements for our proprietary application that only allow delivery of a single executable to the end-user. Normally, to follow the LGPL we could use libproxy as a shared library but given the requirements of the application we cannot.

**Comment by DimStar77** [comment]
Very doubtful.

considering the plugin / module system (i.e. load configs from GNOME/KDE, pacrunners (mozjs, webkit, ductape) being an all-in-one-binary is not even in the design of libproxy
