### ISSUE TITLE
Documentation on proxy tool

### ISSUE THREAD

**Issue by brianjmurrell** [libproxy/libproxy#190]
It would be useful for non-hackers of this project to understand how they can influence various options using the [`proxy`](https://github.com/libproxy/libproxy/blob/master/utils/proxy.c) tool for some things that are less standard than well known env. variables such as `HTTP_PROXY`.

For example, how do you use `proxy` with a PAC URL?

**Comment by brianjmurrell** [comment]
Can anyone please answer the above?

**Comment by janbrummer** [comment]
Depends on how you are using libproxy. libproxy does offer a number of modules to extract the proxy configuration of your preferred desktop environment. E.g. config_gnome3 for GNOME desktop. It just travels your installed modules and uses the first one which says that it is available.

You can debug the application by setting _PX_DEBUG=1 as an environment variable. Then you know exactly which configuration is in use and hopefully know why the output is like it is.

Which system are you using with which desktop envronment?

**Comment by janbrummer** [comment]
Well, actually it is helpful. You are using the pacrunner config extension, thus the configuration is provided through pacrunner. Looks like you want it to respect your environment variables, therefore you'll have to use the config env extension. Just remove all additional config extensions and it should be fine.

**Comment by brianjmurrell** [comment]
> Well, actually it is helpful. You are using the pacrunner config extension, thus the configuration is provided through pacrunner.

Which is a requirement to be able to use JavaScript PAC files, as I understand it, correct?  I.e. there is no other libproxy configuration option that allows PAC files to be executed by a JS engine, is there?

> Looks like you want it to respect your environment variables, therefore you'll have to use the config env extension.

Well, it's not necessarily a case of want.  Don't I **have** to use the env. variables to tell pacrunner how to find the `.pac` file in the case of using the `proxy` command to ensure that _libproxy_ is returning the correct values?

> Just remove all additional config extensions and it should be fine.

Where are config extensions found?  I seem to have installed:

```
$ ls -l /usr/lib64/libproxy/0.4.18/modules/
total 64
-rwxr-xr-x. 1 root root 24728 Jun 21 11:11 config_pacrunner.so
-rwxr-xr-x. 1 root root 33288 Jun 21 11:11 pacrunner_webkit.so
```

If that is at all relevant.

Ultimtely, what I am looking for is to use a PAC file in the GNOME environment.  I have reverted to using the `proxy` tool to test since setting the proxy configuration to Automatic and providing a (local -- i.e. file:///) URL does not seem to be working anymore.  Reporting this as a bug with the GNOME folks they said the problem is with libproxy, not GNOME.

I'm just trying to get back to working GNOME PAC proxy configuration and trying to figure out why it's not working any more.  It was working for a long time and then stopped.

**Comment by janbrummer** [comment]
No, you got it wrong. There are two type of modules within libproxy. The ones starting with config_xx and the ones starting with pacrunner_xxxx-
The first ones are used to extrace the proxy configuration and the later one for parsing the pac files. So at the moment you are asking pacrunner (a dbus service) for it's configuration.

For GNOME you need the config_gnome3 and a pacrunner module (webkit is totally fine, but at the moment i prefer duktape).
As you currently have issues with GNOME and libproxy you may run GNOME under X? Because i just found a bug in libproxy and create a PR to fix it.

**Comment by brianjmurrell** [comment]
> No, you got it wrong.

I'm not at all surprised, hence this ticket to add some _end-user_ type docs on how to config/use libproxy.

> There are two type of modules within libproxy. The ones starting with config_xx and the ones starting with pacrunner_xxxx-

OK.  I just installed an RPM that provides the `/usr/lib64/libproxy/0.4.18/modules/config_gnome3.so` module.  So now I have:

```
$ ls -l /usr/lib64/libproxy/0.4.18/modules/
total 108
-rwxr-xr-x. 1 root root 41608 Jun 21 11:11 config_gnome3.so
-rwxr-xr-x. 1 root root 24728 Jun 21 11:11 config_pacrunner.so
-rwxr-xr-x. 1 root root 33288 Jun 21 11:11 pacrunner_webkit.so
```

It's not lost on me that now I have two config_* modules.  I could just remove the `config_pacrunner.so` one but surely there must be a better way to decide which configuration module one wants to use than just installing/removing `.so` files, yes?

> The first ones are used to extract the proxy configuration and the later one for parsing the pac files.

Understood.

> So at the moment you are asking pacrunner (a dbus service) for it's configuration.

OK.  I guess that is not what I want though?

>For GNOME you need the config_gnome3 and a pacrunner module

Which I do have now, but also have the `config_pacrunner.so` module and `proxy` does seem to be preferring it:

```
$ _PX_DEBUG=1 http_proxy=pac+file:///tmp/test.pac proxy https://login.microsoftonline.com/
Configuration extension is: 26pacrunner_config_extension
Ignored list is: 
Config is: 
	direct://
direct://
```

Is there no better way to force `config_gnome3.so` to be used than to remove `config_pacrunner.so`?

> As you currently have issues with GNOME and libproxy you may run GNOME under X?

I do run GNOME under X, yes.  I would actually say GNOME over X, but that's semantics.  :-)

> Because i just found a bug in libproxy and created a PR to fix it.

Oh!  Maybe this is what I am experiencing then, given that this used to work at some time and then just stopped as of some past update.

So, biting the bullet and (reluctantly) removing `config_pacrunner.so` does seem to have had favourable results:

```
$ _PX_DEBUG=1 proxy https://login.microsoftonline.com/
Configuration extension is: 22gnome_config_extension
Ignored list is: localhost,127.0.0.0/8,::1,*.example.com,example.com,meet.example.com,otcirc.jf.example.com,*.lotus.abc.lab
Config is: 
	pac+file:///home/brian/proxy.pac
PAC received!
Using pacrunner: 26webkit_pacrunner_extension
Pacrunner returned: PROXY proxy-chain.example.com:911
http://proxy-chain.example.com:911
```

Interestingly enough, that Ignore list is coming from the Manual GNOME config.  I would expect that Ignore list to not be used when one changes configuration to Automatic.

So while that achieves my ultimate goal, I am still left with questions of how I can have multiple `config_` modules installed and choose which one is used by different apps/systems.

For example, I might want GNOME apps to use the `config_gnome.so` configuration fetcher but might want to override that and use environment variables for ad-hoc testing of PAC files using the `proxy` testing tool.  I'm not even sure which `config_` module that would be.

**Comment by brianjmurrell** [comment]
Any further comments on the most previous questions?

**Comment by janbrummer** [comment]
There is none.

**Comment by brianjmurrell** [comment]
@janbrummer Thanks for the manpage.  While it does seem to cover the basics of the tool, I still have not found anything that covers the details/questions that were asked previously and yet not answered.

For example, in https://github.com/libproxy/libproxy/issues/190#issuecomment-1283021625 I asked:

OK. I just installed an RPM that provides the /usr/lib64/libproxy/0.4.18/modules/config_gnome3.so module. So now I have:

```
$ ls -l /usr/lib64/libproxy/0.4.18/modules/
total 108
-rwxr-xr-x. 1 root root 41608 Jun 21 11:11 config_gnome3.so
-rwxr-xr-x. 1 root root 24728 Jun 21 11:11 config_pacrunner.so
-rwxr-xr-x. 1 root root 33288 Jun 21 11:11 pacrunner_webkit.so
```

It's not lost on me that now I have two config_* modules. I could just remove the config_pacrunner.so one but surely there must be a better way to decide which configuration module one wants to use than just installing/removing .so files, yes?

If not, is there any point at all in having more than one `config_*` module installed?  Is there any documentation that explains how having multiple `config_*.so`s installed should not really be done, or if it can be how one manages which is used (i.e. by the `proxy` tool or otherwise)?

Should the (i.e) RPM packaging actually enforce that only one `config_*.so` should be installable so as to avoid all of this confusion?

**Comment by janbrummer** [comment]
libproxy has been rewritten and there are no longer plugins at all (they are internal).

**Comment by brianjmurrell** [comment]
Interesting.  Is that rewrite in a released version yet?

Does the rewrite allow per-user/invocation choice of configuration source such as I previously asked about:

> For example, I might want GNOME apps to use the config_gnome.so configuration fetcher but might want to override that and use environment variables for ad-hoc testing of PAC files using the proxy testing tool.

**Comment by janbrummer** [comment]
Not yet, but i'm preparing a 0.5.0 release. You can do this using environment variable: `PX_FORCE_CONFIG=plugin-name`

**Comment by brianjmurrell** [comment]
> Not yet, but i'm preparing a 0.5.0 release.

Awesome!

> You can do this using environment variable: PX_FORCE_CONFIG=plugin-name

Heh, funny enough I just noticed that commit near the tip of _main_.  That's a great addition!

Is there any documentation on how config plugin selection works in absence of `PX_FORCE_CONFIG`?  Maybe that will be coming with the new release documention.

**Comment by janbrummer** [comment]
You mean this one https://libproxy.github.io/libproxy/architecture.html ?
