### ISSUE TITLE
GNOME desktop check is wrong

### ISSUE THREAD

**Issue by janbrummer** [libproxy/libproxy#191]
Current check just accesses DESKTOP_SESSION, but this isn't guaranteed to work under all circumstances. At the moment gnome under X is claiming to be gnome-xorg. As libproxy checks only for gnome or gnome-wayland it fails. Thus no proxy are used on GNOME runnign on X.

A better and recommended way of checking for GNOME is XDG_CURRENT_DESKTOP.

Have a look at: https://gitlab.gnome.org/GNOME/glib-networking/blob/master/proxy/gnome/gproxyresolvergnome.c#L350

**Comment by mcatanzaro** [comment]
Remember it's a colon-separated list of desktops, so it could be "Whatever;GNOME" and should still match as GNOME.
