### ISSUE TITLE
Program crashed when executing `pxgsettings --help`

### ISSUE THREAD

**Issue by xiacunshun** [libproxy/libproxy#198]
`[2022-12-28 03:16:05]>/usr/libexec/pxgsettings --help

(process:639538): GLib-GIO-ERROR **: 03:16:08.478: Settings schema '--help' is not installed
Trace/breakpoint trap (core dumped)`

I guess the reason may be that the function `main` doesn't have strict checks on argv.

`int main(int argc, char **argv) {
•       if (argc < 2) return 1;`

Is there any chance we add '--help' option to pxgsettings or make a more strict check on args?

**Comment by janbrummer** [comment]
Closing as obsolete.
