### ISSUE TITLE
WITH_KDE CMake option doesn't seem to do anything

### ISSUE THREAD

**Issue by tgurr** [libproxy/libproxy#20]
With the recent patches from master regarding KDE handling added to libproxy-0.4.12 trying to disable the build of the KDE module doesn't seem to work. So even with -DWITH_KDE:BOOL=FALSE I end up with a config_kde.so. Either the CMake option should work as intended or removed completely (since it has no build time dependencies anymore). The situation right now is confusing.

**Comment by Vogtinator** [comment]
Try ```-DWITH_KDE=OFF``` and clean your cmake cache.

**Comment by tgurr** [comment]
@Vogtinator I'm always using a clean build environment. I'm not a CMake expert but -DWITH_KDE:BOOL=FALSE should equal -DWITH_KDE=OFF. However I tried your suggestion to make sure and it doesn't work, config_kde.so still gets built and installed.

**Comment by Vogtinator** [comment]
Found it: commit f3019193 by rakuco added a whitespace to the variable.

**Comment by DimStar77** [comment]
fixed in commit 48b7db7
