### ISSUE TITLE
Consider removing support for web proxy autodiscovery, at least for GNOME

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#207]
Web proxy autodiscovery (the protocol used to autodiscover the URL from which to download a web proxy autoconfig file) is dangerous and should probably no longer be supported. Currently there is code to implement this in px-manager.c and hookups to platform-specific settings in config-gnome.c, config-kde.c, config-osx.c, and config-windows.c.

The counterargument here is that if the platform offers a WPAD setting, libproxy should probably respect it because other apps not using libproxy will respect it. So maybe we can't really do anything for KDE (unless we talk to KDE developers about removing wpad), or macOS, or Windows. But I think it's safe to stop respecting the GNOME setting now as the first part of a deprecation plan to get rid of the GNOME setting.

**Comment by mcatanzaro** [comment]
The documentation of px_proxy_factory_get_proxies() also mentions that libproxy will perform WPAD.

**Comment by janbrummer** [comment]
I don't get it. If this is the requested method to access a proxy, then we should respect the configuration. Every admin should be aware that this might be a totally fucked up mess. But this is not the responsibility of libproxy. Or did i get it wrong?

**Comment by janbrummer** [comment]
If GNOME shouldn't use it, remove it from settings. But then you might do have an issue using GNOME in companies...

**Comment by mcatanzaro** [comment]
Users who need web proxy autoconfig should be able to specify the URL manually, right? That doesn't seem so hard?

**Comment by janbrummer** [comment]
Actually the feature of wpad is that the server might change, so no i don't buy it. If i would remove this feature from GNOME i might receive another bug ticket asking for support. But i think we can try to make sure that wpad does not leave the internal network, to fix the security issue...

**Comment by mcatanzaro** [comment]
I was hoping nobody used WPAD anymore. If you really need it, I guess we can keep it around. We should probably make it harder to enable by accident, though, because users see "Automatic" and think good, and then all their network requests start taking forever if their environment doesn't really use WPAD.

Note: [security implications](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol#Security)

**Comment by janbrummer** [comment]
Actually i have just received the info that at least one company is still making use of wpad with an Ubuntu 22.04, so yeah. Will keep this one. At the moment i'm just trying to open http://wpad/, but once this support is extended i'll add libpsl to check the result as well.

**Comment by janbrummer** [comment]
curl also uses libpsl, so this is nothing we should be afraid of :)

**Comment by janbrummer** [comment]
Closing...

**Comment by mcatanzaro** [comment]
Related GNOME issue: https://gitlab.gnome.org/GNOME/glib-networking/-/issues/182
