### ISSUE TITLE
Packaging questions

### ISSUE THREAD

**Issue by mattst88** [libproxy/libproxy#214]
Hello, and congratulations on the release of libproxy-0.5.0!

A few packaging questions from Gentoo:

- What does the libcurl dependency do? From reading `src/backend/px-manager.c` it looks like it's necessary to download the PAC file for automatic proxy configuration?
- Does automatic proxy configuration require both curl and duktape? Or restated, is there a configuration that makes sense to have one but not both?
- Does it make any sense to enable pacrunner support for non-native builds of libproxy? E.g. on the 32-bit build of libproxy on an x86_64 system.

Just a small note: the top-level directory in the release tarball (https://github.com/libproxy/libproxy/archive/refs/tags/libproxy-0.5.0.tar.gz) is named `libproxy-libproxy-0.5.0` which might trip-up distro build systems. Not a big deal, but ideally it would just be named like `libproxy-0.5.0` going forward.

Thanks!

**Comment by janbrummer** [comment]
curl is necessary for PAC file download. Both of them are required at the same time, the reason why there are option is to prevent a build cycle once curl has integrated libproxy support.

Thanks for the hint, i'll fix it soon and release a new version.

**Comment by mattst88** [comment]
Okay, sounds like curl & duktape should only be enabled or disabled together, and the only reason you would build without one or the other is for breaking a circular dependency chain.

**Comment by mattst88** [comment]
I'm struggling to understand despite asking very precise questions. Let me see if trying again helps...

What are the implications of disabling curl+duktape in libproxy? You lose the ability to automatically configure proxies, right? What functionality is left? You can still use libproxy to manually configure proxies, and that's useful because then applications using libproxy don't need to configure proxies themselves, right?

**Comment by janbrummer** [comment]
I'm sorr,y i missed the point that your are preparing an updated version for Gentoo where everything can be compiled individual. Yes. You are right, without curl + duktape you no longer can handle automatic proxies, but manual ones are working fine.

**Comment by janbrummer** [comment]
Every other distribution should of course build everything into the package as you don't know where it is used.

**Comment by mcatanzaro** [comment]
Perhaps instead of two options `pacrunner-duktape` and `curl`, we should have only a single option `pacrunner` since it doesn't make sense to enable one of these without the other, and adding multiple pacrunner backends in the future would be unlikely.

**Comment by mattst88** [comment]
Thank you very much!
