### ISSUE TITLE
Provide a way to install Python bindings for Python 2 and 3

### ISSUE THREAD

**Issue by amigadave** [libproxy/libproxy#22]
In the Fedora packaging, I resorted to a hack in order to install both Python 2 and 3 bindings from the same source tree:

http://pkgs.fedoraproject.org/cgit/rpms/libproxy.git/commit/?id=6b395ee9ae2466a01d8a33bc46353ec18637b040

It would be much better if libproxy did this itself. I had a look at the cmake file for the Python bindings, and it uses the FindPythonInterp module, but that seems quite limited in terms of handling multiple Python versions. OpenCV uses cmake to detect both Python 2 and Python 3, and has some custom handling that might be useful to adapt for libproxy:

https://github.com/Itseez/opencv/blob/master/cmake/OpenCVDetectPython.cmake

**Comment by DimStar77** [comment]
fixed by  #33
