### ISSUE TITLE
libpxbackend should not be public?

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#222]
Since libpxbackend.so does not contain public API and applications are not intended to link to it I don't think it should be installed in the standard library path. It should probably either (a) be installed to a private directory, like /usr/lib64/libproxy, or (b) maybe it should be a static lib instead of a shared lib?

**Comment by janbrummer** [comment]
Right, the purpose of libpxbackend.so has changed during development. For now it does not look like we need it at all and so could also create a simple static one which will be linked in libproxy then...

**Comment by DimStar77** [comment]
Static linking will be hard - as we will have a hard time counter the build cycle.

Moving it to a private location sounds good though

**Comment by smcv** [comment]
> Static linking will be hard

Challenge accepted? :-) #283.
