### ISSUE TITLE
Dependency loop: libproxy -> libsoup -> glib-networking -> libproxy

### ISSUE THREAD

**Issue by 0-wiz-0** [libproxy/libproxy#225]
By default libproxy now requires libsoup.
libsoup requires glib-networking for TLS support (meson stops by default if it's not supplied).
glib-networking would like to use libproxy for `gio/modules/libgiolibproxy.so`, `libexec/glib-pacrunner`, and `share/dbus-1/services/org.gtk.GLib.PACRunner.service`.

So libproxy indirectly depends on itself.

This is a problem for pkgsrc where no loops are supported in the dependencies.
How do you recommend breaking this loop?

**Comment by janbrummer** [comment]
Disable tests and then libproxy does not require libsoup. That's how the build cycle is fixed in OpenSUSE as well.

**Comment by 0-wiz-0** [comment]
Thanks!
