### ISSUE TITLE
Qt5 incompatible config-kde4 still widespread

### ISSUE THREAD

**Issue by Vogtinator** [libproxy/libproxy#23]
It seems like the config-kde4 issue with Qt 5 applications is still very widespread and many are not aware that it is fixed now: https://bugreports.qt.io/browse/QTBUG-52252
Due to the speed regression (#16), the next release should be properly announced (not sure where, kde distribution mailinglist, as they are most likely to need the new version?)

**Comment by mulander** [comment]
The referened OpenBSD crash is actually https://github.com/libproxy/libproxy/issues/24

**Comment by DimStar77** [comment]
A new release (0.4.13) has been published which addresses the issues known.

Whether distributors update or not is out of our control

**Comment by Vogtinator** [comment]
It might be helpful to notify them (e.g. bugtracker) as libproxy doesn't have its own mailing list.
