### ISSUE TITLE
libproxy 0.5.0 build failure

### ISSUE THREAD

**Issue by 0-wiz-0** [libproxy/libproxy#234]
On SmartOS, libproxy 0.5.0 fails to link:
https://us-central.manta.mnx.io/pkgsrc/public/reports/upstream-trunk/20230523.2249/libproxy-0.5.0/build.log
The problem is that it uses symbols like `getnameinfo` that are provided by libsocket on that platform.

Please add a check for libsocket providing getnameinfo and use that when linking (at least for `libpxbackend-1.0.so`).
Thanks!

**Comment by janbrummer** [comment]
Thanks for your report, I'm quiet surprised about this report. Did the previous version 0.4.x worked out of the box? @amigadave was so kind to fix the issue. Could you validate it?

**Comment by 0-wiz-0** [comment]
Yes, the patch fixes the problem. Thanks, @amigadave !

**Comment by 0-wiz-0** [comment]
As for your other question: no, 0.4 had the same issue, but we had a local workaround and I removed it during the 0.5 update.
