### ISSUE TITLE
Building with introspection off but docs on fails

### ISSUE THREAD

**Issue by nanonyme** [libproxy/libproxy#240]
https://github.com/libproxy/libproxy/blob/8121b94c16e87c70910729a428114d03bff9a76f/docs/meson.build#L28 uses libproxy_gir which is only defined when introspection is on. Main meson.build allows enabling docs and disabling introspection but this results in confusing error later in the line instead of being rejected.

**Comment by janbrummer** [comment]
Ohh, nice one. Will fix it

**Comment by janbrummer** [comment]
Quick one, added a comment as otherwise it doesn't make sense at all.
