### ISSUE TITLE
Update from 0.4.x to 0.5.1: various test suites of consumers fail

### ISSUE THREAD

**Issue by DimStar77** [libproxy/libproxy#243]
I prepared updated packages for openSUSE Tumbleweed - and during the integration test we have noticed at least a few consumers failing their testsuites.

This implies that 0.5.x is not as backwards compatible as be expected it to be; some consumers might be willing to adjust, others maybe not so much.

The consumers I identified failing so far were:
 * glib-networking
 * wget (local patch in openSUSE)
 * zypper

**Comment by DimStar77** [comment]
glib-networking fails with

```
test:         environment-libproxy
start time:   06:15:25
duration:     0.17s
result:       killed by signal 6 SIGABRT
command:      G_TEST_SRCDIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/proxy/tests GIO_MODULE_DIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/libproxy GIO_PROXY_TEST_NAME=libproxy G_TEST_BUILDDIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/tests /home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/tests/environment-libproxy
----------------------------------- stdout -----------------------------------
TAP version 13
# random seed: R02S5626e280e2869f33bf5689bd80562f74
1..3
# Start of proxy tests
# Start of environment tests
ok 1 /proxy/environment/uri
ok 2 /proxy/environment/socks
# child process (/proxy/environment/ignore [14415]) exit status: 1 (error)
# child process (/proxy/environment/ignore [14415]) stdout: ""
# child process (/proxy/environment/ignore [14415]) stderr: "**\nGLib-Net:ERROR:../proxy/tests/common.c:190:test_proxy_ignore_common: assertion failed (proxies[0] == \"http://localhost:8080\"): (\"direct://\" == \"http://localhost:8080\")\n"
not ok /proxy/environment/ignore - GLib-Net:ERROR:../proxy/tests/environment.c:72:test_proxy_ignore: child process (/proxy/environment/ignore [14415]) failed unexpectedly
Bail out!
----------------------------------- stderr -----------------------------------
**
GLib-Net:ERROR:../proxy/tests/environment.c:72:test_proxy_ignore: child process (/proxy/environment/ignore [14415]) failed unexpectedly

```

**Comment by janbrummer** [comment]
> glib-networking fails with
> 
> ```
> test:         environment-libproxy
> start time:   06:15:25
> duration:     0.17s
> result:       killed by signal 6 SIGABRT
> command:      G_TEST_SRCDIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/proxy/tests GIO_MODULE_DIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/libproxy GIO_PROXY_TEST_NAME=libproxy G_TEST_BUILDDIR=/home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/tests /home/abuild/rpmbuild/BUILD/glib-networking-2.76.0/x86_64-suse-linux/proxy/tests/environment-libproxy
> ----------------------------------- stdout -----------------------------------
> TAP version 13
> # random seed: R02S5626e280e2869f33bf5689bd80562f74
> 1..3
> # Start of proxy tests
> # Start of environment tests
> ok 1 /proxy/environment/uri
> ok 2 /proxy/environment/socks
> # child process (/proxy/environment/ignore [14415]) exit status: 1 (error)
> # child process (/proxy/environment/ignore [14415]) stdout: ""
> # child process (/proxy/environment/ignore [14415]) stderr: "**\nGLib-Net:ERROR:../proxy/tests/common.c:190:test_proxy_ignore_common: assertion failed (proxies[0] == \"http://localhost:8080\"): (\"direct://\" == \"http://localhost:8080\")\n"
> not ok /proxy/environment/ignore - GLib-Net:ERROR:../proxy/tests/environment.c:72:test_proxy_ignore: child process (/proxy/environment/ignore [14415]) failed unexpectedly
> Bail out!
> ----------------------------------- stderr -----------------------------------
> **
> GLib-Net:ERROR:../proxy/tests/environment.c:72:test_proxy_ignore: child process (/proxy/environment/ignore [14415]) failed unexpectedly
> ```

That's known, because the new libproxy now behave more accurate and the workaround in glib-networking tests is no longer needed and thus failing. Michael is aware of it and it will be updated soon: https://gitlab.gnome.org/GNOME/glib-networking/-/issues/212

**Comment by janbrummer** [comment]
wget: What kind of issue? I've just added it to our client and at the moment it works fine.

**Comment by DimStar77** [comment]
wget - seems the patch needs to be adjusted: https://build.opensuse.org/package/live_build_log/home:dimstar:libproxy/wget/openSUSE_Factory/x86_64 (fails to build)

**Comment by DimStar77** [comment]
> wget - seems the patch needs to be adjusted: https://build.opensuse.org/package/live_build_log/home:dimstar:libproxy/wget/openSUSE_Factory/x86_64 (fails to build)

Updated patch - for reference: https://build.opensuse.org/request/show/1092494 (cflags was not consumed)

**Comment by DimStar77** [comment]
> libzypp build failure: https://build.opensuse.org/package/live_build_log/home:dimstar:libproxy/libzypp/openSUSE_Factory/x86_64

issue seems to be very similar:

```
[  171s] /home/abuild/rpmbuild/BUILD/libzypp-17.31.12/zypp-curl/proxyinfo/proxyinfolibproxy.h:18:10: fatal error: proxy.h: No such file or directory
[  171s]    18 | #include <proxy.h>
[  171s]       |          ^~~~~~~~~
[  171s] compilation terminated.
```


As such, I think the only real issue is https://gitlab.gnome.org/GNOME/glib-networking/-/issues/212 which is not 'our' error, so I'll close the issue.
