### ISSUE TITLE
proxy always returns direct://

### ISSUE THREAD

**Issue by ameansone** [libproxy/libproxy#260]
the problem is, if im not wrong, libproxy always return direct:// when network is unavailable, however, that api(g_network_monitor_get_network_available) to detect network always return false on my machine.

https://github.com/libproxy/libproxy/blob/42b58efd268bc0726dd4ec4e6a37d6ebb5e09cb5/src/backend/px-manager.c#L216C5-L216C5

verbose log
```
$ G_MESSAGES_DEBUG=all proxy http://google.com
(process:923185): GLib-GIO-DEBUG: 03:55:26.851: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(process:923185): GLib-GIO-DEBUG: 03:55:26.866: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(process:923185): pxbackend-DEBUG: 03:55:26.868: px_config_sysconfig_set_config_file: Could not read file /etc/sysconfig/proxy
(process:923185): pxbackend-DEBUG: 03:55:26.869: Active config plugins:
(process:923185): pxbackend-DEBUG: 03:55:26.869:  - config-env
(process:923185): pxbackend-DEBUG: 03:55:26.869:  - config-kde
(process:923185): pxbackend-DEBUG: 03:55:26.869:  - config-gnome
(process:923185): pxbackend-DEBUG: 03:55:26.869:  - config-sysconfig
(process:923185): GLib-GIO-DEBUG: 03:55:26.874: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ?gio-network-monitor?
(process:923185): pxbackend-DEBUG: 03:55:26.874: px_manager_on_network_changed: Network connection changed, clearing pac data
(process:923185): pxbackend-DEBUG: 03:55:26.874: px_manager_constructed: Up and running
(process:923185): pxbackend-DEBUG: 03:55:26.874: px_manager_get_proxies_sync: url=http://google.com online=0
direct://
```

i believe it's related to this issue. 
https://gitlab.gnome.org/GNOME/glib/-/issues/1718

i copied some code from this issue to test. 
https://gitlab.gnome.org/GNOME/glib/-/issues/3177
and it turns out that api never return true before the main loop.

im running latest manjaro kde, not sure if there's something misconfigured on my machine.

ps: i don't understand why it needs to check network first, for me, i would prefer it to be more consistent, maybe we can have some simple way to disable it?

**Comment by ameansone** [comment]
at that simple test program i mentioned, the callback version worked inside main loop, but g_network_monitor_get_network_available never return true.

i noticed theres a callback in libproxy too, is that actually work? since running proxy without arguments didn't work either, maybe proxy does not make use of "glib event loop"? im not familiar with glib ...

any idea to troubleshoot this problem?

and i still prefer to have a way to disable it, i think it does make sense since some proxies is running at localhost, some even do not depend on network at some special cases.


________________________________
发件人: Jan-Michael Brummer ***@***.***>
发送时间: 星期三, 十一月 22, 2023 5:08:28 上午
收件人: libproxy/libproxy ***@***.***>
抄送: ameansone ***@***.***>; Author ***@***.***>
主题: Re: [libproxy/libproxy] proxy always returns direct:// (Issue #260)


I don't think that this is a bug, as in case no network is detected proxy doesn't makes sense. It needs to call this to support automatic proxy server where pac files needs to be downloaded. I'm wondering, why this isn't working on your system...

―

**Comment by ameansone** [comment]
i think these code does not work as intended. as [this issue](https://gitlab.gnome.org/GNOME/glib/-/issues/1718) discussed, applications should not rely on network-available until it get a notify.
https://github.com/libproxy/libproxy/blob/42b58efd268bc0726dd4ec4e6a37d6ebb5e09cb5/src/backend/px-manager.c#L213-L219
by setting `GIO_USE_NETWORK_MONITOR` environment, i can confirm that GNetworkMonitor's non-portal backends work while portal backend does not. calling `g_network_monitor_get_network_available` right after `g_network_monitor_get_default` will never return true, as for that `network-changed` signal, i didn't see it being called for once. so i doubt if it work for anyone with portal backend.

even with this workaround, i still prefer to have a way to disable it, since 1) the api is unreliable, 2) return direct while network is unavailable doesn't make sense either, 3) there're some cases proxy is running at localhost without network.

**Comment by janbrummer** [comment]
Thanks for giving me the hint. Currently not sure how to deal with it.  Is there a valid solution without ignoring network monitor?

**Comment by janbrummer** [comment]
@mcatanzaro As you were part of the discussion in https://gitlab.gnome.org/GNOME/glib/-/issues/1718. Maybe you have a good advice?

**Comment by mcatanzaro** [comment]
The problem here is libproxy doesn't require that applications run a GLib event loop. Without a running event loop, you're just not going to be able to safely use GNetworkMonitor.

How about:

 * If PAC is enabled, just always try to connect and accept that it's going to stall if network is unavailable
 * If PAC is disabled, then you don't need to check whether network is available

would that work?
