### ISSUE TITLE
How are distros supposed to turn of the git hook?

### ISSUE THREAD

**Issue by SuperSandro2000** [libproxy/libproxy#262]
The git hook setup is causing issues in nixpkgs sandbox and it is not worth fixing it for the package build.
I am not sure how to convince meson to not install the git hook here https://github.com/libproxy/libproxy/blob/main/meson.build#L133-L137

Maybe this could just be removed from meson and people interested in using it can manually activate it?

**Comment by janbrummer** [comment]
What's the actual issue on nix?

**Comment by SuperSandro2000** [comment]
The downloaded source code does not contain any git repository to be easier reproducible.

**Comment by janbrummer** [comment]
But the script should stop the installation in case .git is not found...

**Comment by jtojnar** [comment]
The build issue was unrelated – we do not have `/bin/bash` in the build sandbox so we need to run `patchShebangs data/install-git-hook.sh` to fix it.

I do not think installing random shell script without user’s consent when running a build system is a good idea in the first place (see e.g. https://github.com/typicode/husky/issues/468 for a similar issue) but at least the build issue we were having got resolved.

**Comment by smcv** [comment]
> I do not think installing random shell script without user’s consent when running a build system is a good idea in the first place

I would be inclined to agree: git hooks can be useful, but they can also be disruptive to downstream packaging, which is not always "the same shape" as upstream development. If the intention is to put all contributions through formatting/linting to ensure that everything that gets merged is consistent, then having the Github Workflows run formatters, linters etc. before a pull request is merged seems like a better way to achieve that.

**Comment by janbrummer** [comment]
> > I do not think installing random shell script without user’s consent when running a build system is a good idea in the first place
> 
> I would be inclined to agree: git hooks can be useful, but they can also be disruptive to downstream packaging, which is not always "the same shape" as upstream development. If the intention is to put all contributions through formatting/linting to ensure that everything that gets merged is consistent, then having the Github Workflows run formatters, linters etc. before a pull request is merged seems like a better way to achieve that.

It's not a better way, it's actually using more power to achieve it. We shouldn't misuse the CI to fix our local problems. We can add an option which must be enabled manually to skip hook installing. Fine?
