### ISSUE TITLE
Someone help me when ninja -C build

### ISSUE THREAD

**Issue by l16659** [libproxy/libproxy#267]
% ninja -C build
ninja: Entering directory `build'
[1/1] Generating docs/px-doc with a custom command
FAILED: docs/libproxy-1.0 
/opt/homebrew/bin/gi-docgen generate --quiet --add-include-path=/Users/pli/demo_code/build-libproxy/libproxy/docs/src --config=docs/px.toml --output-dir=docs/libproxy-1.0 --no-namespace-dir --content-dir=/Users/pli/demo_code/build-libproxy/libproxy/docs src/libproxy/Libproxy-1.0.gir
ERROR: Could not find GIR dependency in the search paths: Gio-2.0
ninja: build stopped: subcommand failed.

I have installed these:(run on macos)
pip3 install meson ninja
brew install icu4c gobject-introspection duktape gcovr gi-docgen curl vala

**Comment by janbrummer** [comment]
Just have a look at our github action which also builds for OSX: https://github.com/libproxy/libproxy/blob/main/.github/workflows/build.yml#L38
