### ISSUE TITLE
How can I native build a x86_64 arm64 libproxy.dylib(on macos)

### ISSUE THREAD

**Issue by zongyangbigpolo** [libproxy/libproxy#269]
<> libproxy-testok-2.0 % lipo -archs libproxy.dylib'
arm64

(I use the latest libproxy code)
Thank u very much~~

**Comment by l16659** [comment]
host_system = host_machine.system()
if host_system == 'darwin'
    vflag = [
      '-arch', 'x86_64',
      '-arch', 'arm64',
  ]
else
  vflag = []
endif


Above code works for me

**Comment by l16659** [comment]
The above code will occur errors when linking.

**Comment by janbrummer** [comment]
Anything i should add to the code?
