### ISSUE TITLE
Patch to support MacOSX

### ISSUE THREAD

**Issue by pacho2** [libproxy/libproxy#27]
We in Gentoo are applying this patch from macos ports... maybe it could be upstreamed finally:
https://trac.macports.org/browser/trunk/dports/net/libproxy/files/patch-libproxy-cmake.diff

Thanks

**Comment by DimStar77** [comment]
Most of the diffs are just:
```
-if (NOT WIN32 AND NOT APPLE) 
+if (NOT WIN32 AND NOT (APPLE AND MP_MACOSX)) 
```

Which other APPLE setups would need the envvar / GNOME / KDE Plugins?

This change appears rather useless to me.

There is only one diff doing something else:
```
-set_target_properties(libproxy PROPERTIES PREFIX "" VERSION 1.0.0 SOVERSION 1) 
 +set_target_properties(libproxy PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/lib" PREFIX "" VERSION 1.0.0 SOVERSION 1) 
```
Which is certainly not correct for bi-arch distributions...

**Comment by pacho2** [comment]
In our case it's for special setups described in:
https://wiki.gentoo.org/wiki/Project:Prefix

MacPorts project looks to do something similar per its description :/
https://www.macports.org/

**Comment by DimStar77** [comment]
closing stale issue - the patch as-is does not comply and would break other distro use-cases. And the apple and mp_macosx change seems bogus
