### ISSUE TITLE
gnome backend does not fall back to http for https URIs

### ISSUE THREAD

**Issue by jtojnar** [libproxy/libproxy#270]
During the testing of the [Nixpkgs package update](https://github.com/NixOS/nixpkgs/pull/272353), I have noticed the following comment in GSettings schema:

> If an http proxy is configured, but an https proxy is not,
> then the http proxy is also used for https.

The [canonical implementation](https://gitlab.gnome.org/GNOME/glib-networking/-/blob/c31b4748d0a728e7837a00f1e5f517d9c8e8d622/proxy/gnome/gproxyresolvergnome.c#L307) in glib-networking confirms this behaviour.

This does not seem to be respected by libproxy – it treats it as if no proxy was set:

```
(process:150368): pxbackend-DEBUG: 16:19:38.515: px_config_sysconfig_set_config_file: Could not read file /etc/sysconfig/proxy
(process:150368): pxbackend-DEBUG: 16:19:38.515: Active config plugins:
(process:150368): pxbackend-DEBUG: 16:19:38.515:  - config-env
(process:150368): pxbackend-DEBUG: 16:19:38.515:  - config-kde
(process:150368): pxbackend-DEBUG: 16:19:38.515:  - config-gnome
(process:150368): pxbackend-DEBUG: 16:19:38.515:  - config-sysconfig
(process:150368): pxbackend-DEBUG: 16:19:38.521: px_manager_on_network_changed: Network connection changed, clearing pac data
(process:150368): pxbackend-DEBUG: 16:19:38.521: px_manager_constructed: Up and running
(process:150368): pxbackend-DEBUG: 16:19:38.522: px_manager_get_proxies_sync: url=https://github.com/libproxy/libproxy online=1
(process:150368): pxbackend-DEBUG: 16:19:38.522: px_manager_get_proxies_sync: Proxy[0] = direct://
```

<details>
<summary>Reproduction instructions</summary>

Enable manual HTTP proxy and ensure HTTPS proxy is not enabled:

```shell
gsettings reset org.gnome.system.proxy mode
gsettings reset org.gnome.system.proxy.https host
gsettings reset org.gnome.system.proxy.https port
gsettings set org.gnome.system.proxy mode manual
gsettings set org.gnome.system.proxy.http host localhost
```

Then run the following demo program:

```python
import gi
gi.require_version('Libproxy', '1.0')
from gi.repository import Libproxy

url = 'https://github.com/libproxy/libproxy'

pf = Libproxy.ProxyFactory()
proxies = pf.get_proxies(url)
print(proxies)
```

</details>

**Comment by janbrummer** [comment]
That's correct. We are using scheme matching and in case it is not set, we are not falling back to https. That's intended.

**Comment by janbrummer** [comment]
Take a look at https://libproxy.github.io/libproxy/configuration-logic.html . Closing.
