### ISSUE TITLE
proxy.h was moved in 0.5

### ISSUE THREAD

**Issue by jbicha** [libproxy/libproxy#273]
0.4.18 installed this file:

```
/usr/include/proxy.h
```

0.5.3 installs:

```
/usr/include/libproxy/proxy.h
```

This makes this simple test case fail:

```
cat <<EOF > build_test.c
#include <proxy.h>
int main(int argc, char** argv) {
  pxProxyFactory *pf = px_proxy_factory_new();
  if (!pf) return 1;
  return 0;
}
EOF

gcc -o build_test build_test.c -lproxy
```

This version passes because it uses pkgconfig to look up Libs and Cflags.

```
gcc -o build_test2 build_test.c $(pkg-config --cflags --libs libproxy-1.0)
```

This issue was detected by Debian's autopkgtests.

**Comment by janbrummer** [comment]
I'm inclined to close this one, as it works as expected. Am I'm missing something special on Debian side?

**Comment by seb128** [comment]
It's a bit unfortunate since it breaks compatibility with previous version and build for software which aren't using pkgconfig but maybe that's their fault for not using pkgconfig in the first place...

**Comment by jbicha** [comment]
I'm going to close this issue since pkg-config is strongly preferred.

For reference, I also had to link glib manually for libproxy 0.5:

https://salsa.debian.org/gnome-team/libproxy/-/commit/2e6beb2dd
