### ISSUE TITLE
source archive url misbehaving

### ISSUE THREAD

**Issue by jhheider** [libproxy/libproxy#275]
possibly this is an issue that needs to be reported to github directly, but the archive url for v0.5.4 behaves oddly:

https://github.com/libproxy/libproxy/archive/0.5.4.tar.gz
```
the given path has multiple possibilities: #<Git::Ref:0x00007f941e2b99e0>, #<Git::Ref:0x00007f941e2b7e60>
```

the prior release, https://github.com/libproxy/libproxy/archive/0.5.3.tar.gz, behaves normally.

if this needs to be taken away to github, just lmk.

**Comment by kloczek** [comment]
That is result of use the same string in git tag and branch name https://github.com/libproxy/libproxy/issues/276

**Comment by janbrummer** [comment]
Sorry about that... fixed.

**Comment by jhheider** [comment]
very strange manifestation; i'm surprised github behaves that way, and doesn't have a better error.
