### ISSUE TITLE
`url("")` segfaults in 0.4

### ISSUE THREAD

**Issue by bodqhrohro** [libproxy/libproxy#277]
If I have some of proxy environment variables set to an empty string (instead of being unset completely), so `getenv` returns an empty string instead of NULL, the constructor segfaults.

This can be checked as simply as adding `url("");` somewhere in the code, it would crash in this place as well.

**Comment by janbrummer** [comment]
0.4 is obsolete, no further support can be given. Please switch to 0.5.x versions.

**Comment by bodqhrohro** [comment]
Debian Sid still ships 0.4, should I contact their maintainers then? I'm affected because it's still used in glib-networking.

**Comment by bodqhrohro** [comment]
And also, this seems to be caused by compiler optimizations. A whole bunch of variables there are "optimized out", unless I compile with `-DCMAKE_BUILD_TYPE="None"` which disables `-O2`/`-O3` completely, then the exception is thrown correctly. Should I report it to GCC maybe? As `g++-10` was affected, and it's still relevant in `g++-12`.
