### ISSUE TITLE
px_proxy_factory_get_type, px_proxy_factory_copy are not part of a verdef

### ISSUE THREAD

**Issue by smcv** [libproxy/libproxy#281]
px_proxy_factory_get_type() is declared in the public header proxy.h, but is not part of any ELF version definition (verdef) in libproxy.map. Third-party code would normally make use of this symbol via the PX_TYPE_PROXY_FACTORY macro, for example:

```
factory2 = g_boxed_copy (PX_TYPE_PROXY_FACTORY, factory);
```

or while defining a GObject property, something like

```
properties[PROXY_FACTORY] = g_param_spec_boxed ("proxy-factory", NULL, NULL, PX_TYPE_PROXY_FACTORY, ...);
```

Is this intended to be stable ABI that can be used by third-party code? If yes, I would have expected it to be part of a new verdef, which presumably at this point would have to be `LIBPROXY_0.5.5`. Or, if no, it should not be declared in the header and exposed as a public symbol.

Similarly, px_proxy_factory_copy() (the behind-the-scenes implementation of `g_boxed_copy (PX_TYPE_PROXY_FACTORY, .)`) is part of the public ABI even though it is *not* mentioned in proxy.h, and is not part of any ELF version definition. Is this intended to be stable ABI or not? If yes, I would have expected it to be part of a new `LIBPROXY_0.5.5` verdef. Or, if no, it should not be exposed as a public symbol.

**Comment by janbrummer** [comment]
Yes, it should be stable and your points are valid. Could you prepare another PR?
