### ISSUE TITLE
Crash if libproxy is unloaded and loaded again

### ISSUE THREAD

**Issue by keltar** [libproxy/libproxy#285]
Here's a repro example:

```c
#include <libproxy/proxy.h>
#include <dlfcn.h>
#include <stdio.h>

void *libproxy;
pxProxyFactory *(*factory_new)(void);
char **(*get_proxies)(pxProxyFactory *f, const char *url);

static void test_func(void) {
	pxProxyFactory *f = factory_new ();
	char **v = get_proxies (f, "https://www.amazon.com");
	printf("%p %p\n", f, v);
}

int main(int argc, char **argv) {
	libproxy = dlopen("libproxy.so", RTLD_NOW | RTLD_LOCAL);
	factory_new = dlsym(libproxy, "px_proxy_factory_new");
	get_proxies = dlsym(libproxy, "px_proxy_factory_get_proxies");
	test_func();
	dlclose(libproxy);

	libproxy = dlopen("libproxy.so", RTLD_NOW | RTLD_LOCAL);
	factory_new = dlsym(libproxy, "px_proxy_factory_new");
	get_proxies = dlsym(libproxy, "px_proxy_factory_get_proxies");
	test_func();

	return 0;
}
```

When builded somehow like this `gcc -pipe -Wall test.c $(pkg-config glib-2.0 --cflags) -O0 -g3 -ld` it crashes on second lookup. The problem seems to be it loses glib type information (saved as global variable?) and tries to register type again, which fails.

Yandex-disk linux client seems to be doing dlopen/dlclose things under the hood, rendering it unusable with libproxy-0.5+. With LD_PRELOAD it works fine.

Maybe there is a way to handle that on libproxy side?

**Comment by keltar** [comment]
https://discourse.gnome.org/t/libraries-that-use-glib-sometimes-need-to-use-glibs-link-flags-whats-the-best-way-to-achieve-this/7487/8 it appears this is a common problem with any library using gobject. Should I make a pull request with `-z,nodelete` linker flags? Other solutions look much more cumbersome.

**Comment by janbrummer** [comment]
Thanks for the hint, I've created a PR.
