### ISSUE TITLE
Is DIRECT in wpad supported?

### ISSUE THREAD

**Issue by lovetox** [libproxy/libproxy#304]
We have a wpad.dat file that ends in

`"PROXY 2.3.4.5:3128; PROXY 2.3.4.6:3128; DIRECT";`

when libproxy resolves it we get in the log

```
(org.gajim.Gajim:21540): pxbackend-DEBUG: 23:13:14.101: px_manager_get_proxies_sync: url=none://xmpp.company.de:5222 online=1
(org.gajim.Gajim:21540): pxbackend-DEBUG: 23:13:14.101: px_manager_get_proxies_sync: Config[0] = wpad://
(org.gajim.Gajim:21540): pxbackend-DEBUG: 23:13:14.101: px_manager_get_proxies_sync: Proxy[0] = http://2.3.4.5:3128
(org.gajim.Gajim:21540): pxbackend-DEBUG: 23:13:14.117: px_manager_get_proxies_sync: Proxy[1] = http://2.3.4.6:3128
```

if i look into https://github.com/libproxy/libproxy/blob/main/src/backend/px-manager.c#L475

there seems to be no handling for the DIRECT keyword? Do i read the code correct?

The intention here would be, if the two proxies are not available or not suiteable for the protocol try as last resort direct connection.

We use internally GLib.ProxyResolver, and it does not try the direct method, it only tries the two proxies, our guess from the code in px-mamanger.c `px_manager_run_pac` is that it does not return `direct://`  to GLib in this case as an option?

And if the wpad file only contains `return DIRECT` this could be working by accident, as its not handled currently, the list of proxies would be empty and in this case libproxy adds manually `direct://` in https://github.com/libproxy/libproxy/blob/main/src/backend/px-manager.c#L684

**Comment by janbrummer** [comment]
Could you please try this new PR and check whether it solves your problem?

**Comment by lovetox** [comment]
A user of our application reported this problem to us, its sadly much work to build this and send a custom build to the user for testing.

I reviewed the MR, and it looks good to me.

We will test it as soon as we do our next application release and include a new version of the lib.

Thanks for the fast reaction.

**Comment by zak333** [comment]
We have the described problem and are unable to connect anymore using the latest libproxy version.
Unfortunately I cannot easily build libproxy for use on windows to test this. Is there someone who can provide a libproxy.dll I can test?

On the other hand I think the change seems trivial enough to merge?

I was thinking though, if `direct://` maybe should _always_ be added as last proxy. The default if no proxy was found is already `direct://`, so this makes sense to me. It is just a minor detail of course.

**Comment by zak333** [comment]
I just tested the latest application snapshot including libproxy 0.5.8 on Windows and it does indeed solve the problem.

The log messages are now:
```
(org.gajim.Gajim:15708): pxbackend-DEBUG: 18:58:29.386: px_manager_get_proxies_sync: url=none://xmpp.company.de:5222 online=1
(org.gajim.Gajim:15708): pxbackend-DEBUG: 18:58:29.393: px_manager_get_proxies_sync: Config[0] = wpad://
(org.gajim.Gajim:15708): pxbackend-DEBUG: 18:58:29.402: px_manager_get_proxies_sync: Proxy[0] = http://2.3.4.5:3128
(org.gajim.Gajim:15708): pxbackend-DEBUG: 18:58:29.406: px_manager_get_proxies_sync: Proxy[1] = http://2.3.4.6:3128
(org.gajim.Gajim:15708): pxbackend-DEBUG: 18:58:29.409: px_manager_get_proxies_sync: Proxy[2] = direct://
```
Thank you for the fix.
