### ISSUE TITLE
ReversedException not considered in KDE backend

### ISSUE THREAD

**Issue by IlyaBizyaev** [libproxy/libproxy#311]
*(This is a drive-by report for what I think is an issue)*

In KDE Plasma's System Settings, the manual proxy configuration has a checkbox labeled “Use proxy settings only for addresses in the Exceptions list” (stored as `ReversedException`). As far as I understand, it reverses the meaning of “Exceptions” (`NoProxyFor`) from a blocklist to an allowlist.

From a brief look at libproxy, it doesn't seem like this reversal is considered.

Here's an example handling code in Chromium:
https://source.chromium.org/chromium/chromium/src/+/main:net/proxy_resolution/proxy_config_service_linux.cc;l=802;drc=8e948282d37c0e119e3102236878d6f4d5052c16

**Comment by janbrummer** [comment]
Weird, never seen this before. But fine, should be doable.
