### ISSUE TITLE
Update doc for a Windows build (+ add MSVC?)

### ISSUE THREAD

**Issue by TroudhuK** [libproxy/libproxy#315]
I failed to build libproxy for Windows following [the doc](https://libproxy.github.io/libproxy/build-steps.html#windows-msys2) (because of dependencies, GLib mainly). Can you update it?

And can you detail step by step how to build libproxy static and dynamic with MSVC on Windows from scratch (= how to deal with dependencies, maybe build them...)?

**Comment by janbrummer** [comment]
What's the issue you are facing?

**Comment by TroudhuK** [comment]
You just have to follow the doc and you will see that from the very first line, it doesn't work. Then I'm facing my ignorance (I don't know GTK, meson, ninja, ...) and lack of time to discover what to do (I found that mingw-w64-x86_64-glib is no more used and we have to use something with glib2...).

Furthermore, even if I successfully build something with a lot of MSYS dependencies (I did after some hours of research, problem to get pkg-config etc...), I want to do it with MSVC instead, and to avoid reinventing the wheel I ask to the community if someone successfully did it and have a recipe.

**Comment by nmoinvaz** [comment]
As far as I know, libproxy is intended to be a system library and not intended for static compilation which may violate the license. I have started a separate project https://github.com/nmoinvaz/proxyres which addresses some of these issues.

**Comment by TroudhuK** [comment]
Thank you for sharing your project which not well referenced.

I haven't looked into licensing issues yet since at this stage I just wanted to test, but static compilation is not mandatory (just, I'd like to avoid adding dependencies to other redistributable, like MSYS or MinGW, if I can build for MSVC).

I will have a look to proxyres which seems to perfectly answer to my needs.

**Comment by janbrummer** [comment]
Thanks for the hint, I've updated the doc page. This library is used as shared lib and not as static. Cannot help you with MSVC, sorry.
