### ISSUE TITLE
Please update to libmozjs 24

### ISSUE THREAD

**Issue by bigon** [libproxy/libproxy#32]
Hi,

libproxy currently uses libmozjs 1.8.5 which is quite old.

Would be nice if it was updated to use libmozjs 24

Thanks

**Comment by jlinton** [comment]
I have the patches for this and will be posting them shortly assuming they get through the company IP review.

Can you test them (testing them has been a bit of a problem)

**Comment by jlinton** [comment]
Ok, that was painless this time. Check the pull requests for the patch.

https://github.com/libproxy/libproxy/pull/36

**Comment by yan12125** [comment]
+1 for updating targetting mozjs version

By the way, GNOME is moving to mozjs31: https://git.gnome.org/browse/gjs/log/?h=wip/ptomato/mozjs31. How about re-target libproxy to mozjs 31 instead? Or even crazy, mozjs45? I have a patch for mozjs45 that runs fine with the simplest PAC.

**Comment by nullr0ute** [comment]
I would be +1 for mozjs45 (or even 52 which is due out soon and will be another LTE)

**Comment by DimStar77** [comment]
Agreed - 45 would be a nice target

**Comment by Keruspe** [comment]
Now that 52 is out and is an LTE too, it's definitely the best choice, imo

**Comment by yan12125** [comment]
@Keruspe Do you know where I can find a source tarball for js52? https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases doesn't have it.

**Comment by Keruspe** [comment]
@yan12125 https://ftp.mozilla.org/pub/firefox/releases/52.0esr/source/firefox-52.0esr.source.tar.xz

**Comment by bigon** [comment]
FTR it seems that GNOME and polkit are moving to mozjs38

Would be a better idea to use that version and stick to GNOME?

**Comment by nullr0ute** [comment]
Yes, or even a newer version. Latest LTR is 52 I believe

**Comment by jlinton** [comment]
I've been doing the rounds for pacrunner and polkit, with updates to mozjs38. Let me see about a patch for libproxy as well.

**Comment by Keruspe** [comment]
@DimStar77 could we get a new release now that the port to spidermonkey 38 has been merged?

And maybe close this issue and open a new one for a port to spidermonkey 52?

**Comment by DimStar77** [comment]
@Keruspe - Thanks for the reminder.. I tagged 0.4.15 and published it.

Let's close this issue for now. Thank you all for working on this and helping moving this forward!
