### ISSUE TITLE
GMCS script not found with Mono 4.6

### ISSUE THREAD

**Issue by gdsotirov** [libproxy/libproxy#37]
I found it problematic to build libproxy on Slackware 14.2 with Mono 4.6, because gmcs wrapper script is no more available. The difference is only in the command line arguments (checked on Slackware 14.1 with Mono 3.12) as clear from outputs below:

`$ cat /usr/bin/gmcs
#!/bin/sh
exec /usr/bin/mono $MONO_OPTIONS /usr/lib/mono/4.5/mcs.exe -sdk:2 "$@"`

` cat /usr/bin/mcs
#!/bin/sh
exec /usr/bin/mono $MONO_OPTIONS /usr/lib/mono/4.5/mcs.exe "$@"`

So I decided to create a small patch accessible from [here](http://sotirov-bg.net/viewvc/viewvc.cgi/cvs/projects/sh/slackbuilds/l/libproxy/libproxy-0.4.13.diff?revision=1.1&view=co). Should gmcs be replaced with mcs upstream to avoid the issue?

**Comment by DimStar77** [comment]
This is indeed something we should be changing - Mono 2 is quite dead and should stay that way
