### ISSUE TITLE
Properly build and install the Ruby binding

### ISSUE THREAD

**Issue by paulvt** [libproxy/libproxy#42]
When running `configure`/`make`/`make install`, the Ruby binding is not build nor installed.
To manually build and install, I currently do (for the default Ruby version):

```
$ cd bindings/ruby
$ ruby extconf.rb
$ RUBY_ARCH_DIR=$(shell ruby -rrbconfig -e 'puts RbConfig::CONFIG["vendorarchdir"]')

$ swig -ruby Libproxy.i
$ make

$ make install RUBYARCHDIR=$RUBY_ARCH_DIR
```

**Comment by johan-smits** [comment]
This would be nice to have in our project to

**Comment by janbrummer** [comment]
Closing as obsolete., ruby example are available.
