### ISSUE TITLE
Clients cannot free() data that we allocated

### ISSUE THREAD

**Issue by dwmw2** [libproxy/libproxy#43]
In a Windows process, there can be multiple per-library heaps. It is not generally possible for something to be allocated in one library, then freed in another.

Our client API forces this to happen, with an application freeing the results returned by `px_proxy_factory_get_proxies()`.

Much as I hate to change an API that has been stable for almost a decade, can we add a new function to free those results instead of making the caller do so? Obviously it can be optional and we don't have to break compatibility with existing callers. But callers who previously avoided libproxy because "we support Windows and we can't do that" would be able to use it if they want.

**Comment by thiagomacieira** [comment]
Any update?

**Comment by Vogtinator** [comment]
(FYI: The maintainer is currently on vacation for several weeks)

Everything needed would be a function

```
void px_proxy_factory_free_proxies(char **proxies)
{
    if (!proxies)
        return;

    while (*proxies)
        free(*proxies++);

    free(proxies);
}
```

right? AFAICT that wouldn't break backwards-compat with callers that worked fine with manual `free`ing previously.

**Comment by thiagomacieira** [comment]
That is correct.

**Comment by DimStar77** [comment]
commit d52cc34458b1d6a524df12db2671fa3a15892fcf introduced a new API call px_proxy_factory_free_proxies, which can be used to have the library free its own memory space

This will be part of libproxy 0.4.16
