### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by piotr-dobrogost** [libproxy/libproxy#52]
For example at https://github.com/libproxy/libproxy/wiki/GetInvolved , there is the following phrase
> Look for holes in the current documentation

but no link...

In [doc](https://github.com/libproxy/libproxy/tree/master/doc) source directory there's only [libproxy_files.dia](https://github.com/libproxy/libproxy/blob/master/doc/libproxy_files.dia) file...

**Comment by DimStar77** [comment]
All the doc we currently have is the wiki - and yes, it is one big hole :(
