### ISSUE TITLE
network manager plugin not built

### ISSUE THREAD

**Issue by frispete** [libproxy/libproxy#53]
while the deps are are found:

```
[   34s] -- checking for modules 'libnm;dbus-1'
[   34s] --   package 'libnm' not found
[   34s] -- checking for modules 'NetworkManager;dbus-1'
[   34s] --   found NetworkManager, version 0.9.10.0
[   34s] --   found dbus-1, version 1.8.22
[   34s] -- checking for one of the modules 'mozjs185'
[   34s] -- checking for module 'natus'
[   34s] --   package 'natus' not found
[   34s] -- checking for module 'javascriptcoregtk-4.0'
[   34s] --   found javascriptcoregtk-4.0, version 2.6.6
[   34s] MODULES TO BUILD:
[   34s]        *       config_envvar
[   34s]        *       config_sysconfig
[   34s]                config_gnome
[   34s]        m       config_gnome3
[   34s]                config_kde
[   34s]                config_macosx
[   34s]                config_w32reg
[   34s]        *       ignore_domain
[   34s]        *       ignore_hostname
[   34s]        *       ignore_ip
[   34s]                network_networkmanager
[   34s]                pacrunner_mozjs
[   34s]                pacrunner_natus
[   34s]        m       pacrunner_webkit
[   34s]        *       wpad_dns_alias
```
if I interpret `libproxy/cmake/modules/network_networkmanager.cmk` correctly:
```
if (NOT WIN32 AND NOT APPLE)
  px_check_modules(NM libnm dbus-1)
  if (NOT NM_FOUND)
    px_check_modules(NM NetworkManager dbus-1)
  endif (NOT NM_FOUND)
endif()
```
NM_FOUND should be set, which is tested in `libproxy/cmake/modules.cmk`:
```
px_module(network_networkmanager   "${NM_FOUND}"     0       ${NM_LIBRARIES})
```
This happens with `cmake 3.3.1` in a openSUSE Build Service [project](https://build.opensuse.org/package/show/home:frispete:PyQt5/libproxy-plugins) for `openSUSE 13.2` at least.

This used to built correctly, and was badly needed, as `zeal` failed to run with a segfault otherwise (again on 13.2).

**Comment by DimStar77** [comment]
@frispete This was tested with libproxy 0.4.14 ? Or what version did you try to build?

**Comment by DimStar77** [comment]
Can you please verify if pull request #54 works for you? I tested it with NM 1.4 and this at least works (again, after some trial and error); autofoo handles this nicer imho :)

**Comment by frispete** [comment]
Do you have an idea, how I get to the diff of your PR? Would like to apply it in the rpm build directly...

**Comment by frispete** [comment]
Okay, no easy way, I fetched it from a clone of your repo, and it builds!

OTOH and OT, it triggers a somewhat scary rpmlint warning:
```
[   72s] libproxy1-config-gnome3.x86_64: E: shlib-fixed-dependency (Badness: 440) libproxy1 = 0.4.14
[   72s] Your shared library package requires a fixed version of another package. The
[   72s] intention of the Shared Library Policy is to allow parallel installation of
[   72s] multiple versions of the same shared library, hard dependencies likely make
[   72s] that impossible. Please remove this dependency and instead move it to the
[   72s] runtime uses of your library.
```

I didn't notice, that cmake is such a beast, autotools were a huge pile of macro trash, and now cmake fails in pretty ugly ways..

**Comment by DimStar77** [comment]
I don't think that rpmlint warning is new for openSUSE (It's also present in openSUSE:Factory)

As for the pull req: thanks for testing - I will merge this diff then (and keep on hating cmake)

**Comment by DimStar77** [comment]
btw: as for getting a patch: simply add '.patch' to the URL, eg: https://patch-diff.githubusercontent.com/raw/libproxy/libproxy/pull/54.patch

**Comment by frispete** [comment]
Nice trick. Thanks Dominique! No idea, why there's no link displayed for this functionality.
