### ISSUE TITLE
gsettings plugin is spawning a shell to start the helper

### ISSUE THREAD

**Issue by bigon** [libproxy/libproxy#57]
Hi,

At least libproxy/modules/config_gnome.cpp and libproxy/modules/config_gnome3.cpp are using the following pattern:

	execl("/bin/sh", "sh", "-c", program, (char*) NULL);

Why is it spawning a shell before spawning the helper command?

**Comment by DimStar77** [comment]
@npmccallum Do you remember why you did it this way? I sort of assume it has to do with 'using sh to find the path' of ```program```

**Comment by bigon** [comment]
I don't think it's needed to spawn a shell for that:

```
   Special semantics for execlp() and execvp()
       The execlp(), execvp(), and execvpe() functions duplicate the actions of the shell in searching for an executable file if the specified filename does not contain a slash (/) character.  The file  is
       sought in the colon-separated list of directory pathnames specified in the PATH environment variable.  If this variable isn't defined, the path list defaults to the current directory followed by the
       list of directories returned by confstr(_CS_PATH).  (This confstr(3) call typically returns the value "/bin:/usr/bin".)

       If the specified filename includes a slash character, then PATH is ignored, and the file at the specified pathname is executed.
```

**Comment by bigon** [comment]
Wait no, I don't think it's fixed, 8012bed4405efa31fffb57d6282de3e1513e4bd9 still uses `execl()` which is not searching the path, according to the doc above you need `execlp()`

**Comment by bigon** [comment]
*sigh*

OK I now see why it was using /bin/sh to start the helper.

It's because the code is concatenate the gsettings keys to watch (in all_keys) as parameters

So this is not enough to just remove /bin/bash

**Comment by bigon** [comment]
Anyway, until a proper solution is found, 8012bed4405efa31fffb57d6282de3e1513e4bd9 needs to be reverted IMHO

**Comment by DimStar77** [comment]
https://github.com/libproxy/libproxy/pull/91 - reverting
