### ISSUE TITLE
networkmanager plugin not working

### ISSUE THREAD

**Issue by bigon** [libproxy/libproxy#58]
Hi,

I've the feeling that the networkmanager plugin is not working:

Test case:

0. Set the URL to a pac file in the `gnome-control-center` panel
1. Start the `proxy` command without any URL
2. Type an URL, and get the result (here you can see in the logs of the webserver that the .pac file has been downloaded)
3. Disconnect and reconnect the network using the `gnome-control-center` panel
4. Type an URL again, I would expect that the pac file is re-downloaded, but I cannot see anything in the logs

I cannot see the "Network changed" string from `libproxy/proxy.cpp` either

**Comment by bigon** [comment]
OK so apparently the rule in the `dbus_bus_add_match()` call is wrong, changing, the following diff is fixing the issue:

```diff
-                       dbus_bus_add_match(conn, "type='signal',interface='" NM_DBUS_INTERFACE "',member='StateChange'", NULL);
+                       dbus_bus_add_match(conn, "type='signal',interface='" NM_DBUS_INTERFACE "',member='StateChanged'", NULL);
```

`StateChange` is defined as `NM_DBUS_VPN_SIGNAL_STATE_CHANGE` in the `NetworkManager/NetworkManagerVPN.h` header though.

**Comment by bigon** [comment]
Apparently `StateChange' has been deprecated since 0.7 and completely removed in 0.9, see https://developer.gnome.org/NetworkManager/0.9/ref-migrating.html

**Comment by DimStar77** [comment]
Thanks for chasing this down; much appreciated.

Would you like to create a pull request with the diff you proposed (then the change is properly attributed to you) - otherwise I'll just prepare one - it's as you wish

**Comment by bigon** [comment]
I'll do that later today
