### ISSUE TITLE
[patch] Resource leak/crash on Windows

### ISSUE THREAD

**Issue by fraca7** [libproxy/libproxy#62]
On Windows, sockets should be closed using closesocket() and not close(). Failing to do so results in:

1. A leak on older MSVC runtimes (or even closing an unrelated regular file)
2. A crash on newer versions

The attached patch fixes this.

[libproxy-closesocket.txt](https://github.com/libproxy/libproxy/files/1018403/libproxy-closesocket.txt)

**Comment by DimStar77** [comment]
@fraca7 Thank you for your contribution! could you please make a github pull request? That will have the advantage of giving you proper attribution in the commit history as well.

**Comment by fraca7** [comment]
Will do tomorrow.

**Comment by DimStar77** [comment]
Fixed with https://github.com/libproxy/libproxy/commit/642c2ec2e6547aaf19ff63257f867c7c50b0dd77
