### ISSUE TITLE
Return WPAD and/or PAC URLs

### ISSUE THREAD

**Issue by thiagomacieira** [libproxy/libproxy#67]
Please add a way for users of the library to obtain the URLs for the WPAD and/or PAC, without libproxy interpretation. That might be useful if the caller library already has a JS engine or PAC interpreter of its own.

**Comment by npmccallum** [comment]
I don't see any value in this. Can you explain your use case?

**Comment by thiagomacieira** [comment]
I did: the calling library already has a JS engine it could use, so we may want to avoid loading yet another by way of libproxy plugins.

**Comment by npmccallum** [comment]
But libproxy will already attempt to use the JS engine of the calling application. So there isn't any value in making the application do additional work.

**Comment by thiagomacieira** [comment]
I'm not seeing any API for the calling library to specify which plugin to load. 

Or, better yet, to specify a module extension that is already loaded. The extension_pacrunner.hpp file is not installed, so we cannot provide our own hosted extensions.

**Comment by npmccallum** [comment]
https://github.com/libproxy/libproxy/blob/master/libmodman/module_manager.cpp#L98

PAC Runner modules use this feature of libmodman. They specify a symbol to look for in the current symbol space. Based on this, we prefer modules that are already loaded by your app. In short, you don't need to do anything. If there is a JS engine already loaded and we support it, we will use it. Otherwise, we'll load one (which one we load is undefined).

**Comment by thiagomacieira** [comment]
After some investigation, I think I understand how this works. Please correct me if I'm wrong: each plugin declares the name of a library and the name of a symbol that will be searched for in the current process. If those symbols are found, that plugin is preferred above all others (https://github.com/libproxy/libproxy/blob/master/libproxy/modules/pacrunner_webkit.cpp#L171, https://github.com/libproxy/libproxy/blob/master/libproxy/modules/pacrunner_mozjs.cpp#L197).

Even if that's the case, there are several problems with that solution.

First, I can't specify a C++ symbol. If my JS engine library is written entirely in C++ (as QtQml is), I'd need to add a dummy C function to it so it can be found by libmodman.

Second, that's a dependency cycle. If the plugin must be provided by libproxy, then the JS engine (like QtQml) needs to exist before libproxy is compiled. But in order to compile the library that provides the JS engine, we need libproxy to have been compiled (because QtNetwork uses libproxy). Something needs to break this cycle.

Third, even if the JS engine were provided as a built-in, all the other JS engine plugins will be loaded into memory (https://github.com/libproxy/libproxy/blob/master/libproxy/proxy.cpp#L165 → https://github.com/libproxy/libproxy/blob/master/libmodman/module_manager.cpp#L328 → https://github.com/libproxy/libproxy/blob/master/libmodman/module_manager.cpp#L251). That dlopen() call needs to be avoided in the first place.

**Comment by thiagomacieira** [comment]
1. Possible, but ugly, with a lot of #ifdef so we can catch the different MSVC manglings.
2. No, they don't and that's actually easy to fix. Just install extension_pacrunner.hpp and we can build our own plugin inside Qt.
3. dlopen() loads the plugin, regardless of whether you use it or not and regardless of whether RTLD_LAZY was passed. dlclose()ing it afterwards only makes the matter worse if you're going to reload later. I want to avoid the dlopen() cost altogether. This is especially important for C++ libraries because they may have load-time code being run, which may be non-negligible, and may even crash if there are incompatible libraries already loaded in memory.

So I have two asks:
* Provide a way for Qt to offer its own PAC runner extension, without creating a dependency cycle.
* Do not dlopen any plugins for an extension that Qt already provided.

**Comment by npmccallum** [comment]
This basically boils down to a rewrite. I'm not against a rewrite, but I'm not going to do it. If you want to take over leadership of the project and invest the time in it, I don't have any problem. @DimStar77 is doing most of the work these days. But I don't think libproxy is seeing active development (just basic maintenance).

You should, however, be aware that libproxy is used on Win32, Mac and Linux across multiple desktop environments. So you have to make it work for everyone. That represented a lot of effort in the past on my part. And I don't have time to dedicate to it these days.

**Comment by thiagomacieira** [comment]
A rewrite isn't necessary. An update to libmodman so that it scans the plugin files without dlopen()ing them, installing the necessary extension_*.hpp files and providing an API to install extensions would go a long way.

As for a rewrite, there already are. connman-pacrunner, for example, has a replacement of libproxy (https://git.kernel.org/pub/scm/network/connman/pacrunner.git/)

**Comment by andy-shev** [comment]
> An update to libmodman so that it scans the plugin files without dlopen()ing them, installing the necessary extension_*.hpp files and providing an API to install extensions would go a long way.

Just out of my curiosity, how you scan plugin files w/o `dlopen()` and what is a benefit of it? Do you have exhausted virtual address space or what?

> As for a rewrite, there already are. connman-pacrunner, for example, has a replacement of libproxy (https://git.kernel.org/pub/scm/network/connman/pacrunner.git/)

So, why not to use it?

**Comment by thiagomacieira** [comment]
See my reply from [2017-07-18](https://github.com/libproxy/libproxy/issues/67#issuecomment-316193959). The problem with dlopening the plugin is that at will load all the dependencies, direct and indirect. That's a lot of relocations to be resolved for big JS engine libraries. But more importantly, any C++ libraries in the chain can also declare variables that require dynamic initialisation and that will be run before `dlopen` returns. Big JS libraries have a lot of that. So the scan for the right library can take non-negligible time.

I concede that it happens once only, though.

As for how you can scan prior to `dlopen`, just open the file, search for a magic string in the file and then read from there the symbol that you must search for or other conditions that must be met. You can also solve this by having an extra, text file next to the plugin describing the plugin and the conditions.

I also gave an other proposal which was to install a simple header file so we could provide our own plugin from QtNetwork.

> Do you have exhausted virtual address space or what?

It's not about the virtual address space, it's the resident set memory. Each library loaded into memory contributes at least 4 kB of non-shareable memory, but often more for big JS engines. JavaScriptCoreGtk for example 0x0784e0 rounded up to one page (so 0x079000), so 494 kB per process it is loaded in.

I'm simply trying to help libproxy's loading. I *know* that I have a JS engine, I don't need libproxy / libmodman to guess.

> So, why not to use it?

I do use it on my own systems, but that's all. Do you want me to lobby Linux distributions to use its libproxy instead of libproxy's?

**Comment by andy-shev** [comment]
@thiagomacieira 
Okay, you have few choices here:
* move to a better library (with or without trying to push distributions to move as well)
* fix this library
* don't use PAC approach at all (I hope you understand that the whole PAC idea is brain damaged from the day 1 because of JS engine to be used)

**Comment by thiagomacieira** [comment]
I completely agree on that last one. It would have been much better if it were a config file instead of a script... but unfortunately it's not our call.

Anyway, I've reported the request and the issue is real. It's up to maintainers to decide whether they want to do something about ti or not.

**Comment by Vogtinator** [comment]
Note that libproxy is going to change significantly in the next version with PR #157 merged. That way there's no script engine per process at all, but only per session, so this shouldn't be necessary.

**Comment by thiagomacieira** [comment]
Thanks, that's good to know.
