### ISSUE TITLE
Port to mozjs52

### ISSUE THREAD

**Issue by bigon** [libproxy/libproxy#71]
Hi,

mozjs 52 is the new mozjs release, I guess that libproxy should be ported to that version

**Comment by DimStar77** [comment]
it should, indeed

**Comment by bigon** [comment]
Mhhh it seems that the merged patch is missing a call to `JS::InitSelfHostedCode`

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/How_to_embed_the_JavaScript_engine
