### ISSUE TITLE
Please upload release tarballs

### ISSUE THREAD

**Issue by rossburton** [libproxy/libproxy#73]
The 0.4.14 release has a proper uploaded tarball (https://github.com/libproxy/libproxy/releases/tag/0.4.14) but the 0.4.15 (https://github.com/libproxy/libproxy/releases/tag/0.4.15) only has the generated tarballs and not a static maintainer-generated tarball.

The problem with this is that the generated tarballs can and do change over time, so there's no way that distributions can use a checksum to verify that the download tarball has been corrupted or tampered with.  Please could you generate and upload a static tarball.

**Comment by DimStar77** [comment]
I just uploaded a libproxy-0.4.15.tar.xz; ws do have it documented in the release process; yet it did not happen. Apologies for that.
