### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by tejohnso** [libproxy/libproxy#74]
It looks like the wiki page for [windows builds](https://github.com/libproxy/libproxy/wiki/WindowsPort) hasn't been updated in a while. Does this project still build on Windows? 

 I'm getting a lot of errors in *VS Community 2017*. Initially it was a unistd.h error so I installed MinGW and added its include dir but that only surfaced more errors.

I also tried cmake -G "MinGW Makefiles" to install with MinGW directly but again ran into an error wall.

**Comment by janbrummer** [comment]
Closing as obsolete.
