### ISSUE TITLE
WITH_WEBKIT option not applied?

### ISSUE THREAD

**Issue by jtojnar** [libproxy/libproxy#75]
The INSTALL file mentions a `WITH_WEBKIT` option:

https://github.com/libproxy/libproxy/blob/5c19cfe944ace2645e19f79c0c1008fea984040b/INSTALL#L119

but it is not used anywhere. Perhaps the following line should use it?

https://github.com/libproxy/libproxy/blob/5c19cfe944ace2645e19f79c0c1008fea984040b/libproxy/cmake/modules/pacrunner_webkit.cmk#L23

**Comment by hamishmack** [comment]
I think it is used here https://github.com/libproxy/libproxy/blob/5c19cfe944ace2645e19f79c0c1008fea984040b/libproxy/cmake/pkgconfig.cmk#L7-L8 when called from https://github.com/libproxy/libproxy/blob/5c19cfe944ace2645e19f79c0c1008fea984040b/libproxy/cmake/modules/pacrunner_webkit.cmk#L24

**Comment by jtojnar** [comment]
You are right, I was confused by the matching `else` construct and mistook it for `elseif`.
