### ISSUE TITLE
socks URI is not versionned

### ISSUE THREAD

**Issue by gnumdk** [libproxy/libproxy#78]
libproxy set socks URI as socks:// for GNOME 3 module.

It does not work with pip3 for example, it should be set to socks4:// as GNOME does not handle socks versionning.

**Comment by npmccallum** [comment]
Please read the documentation:
https://github.com/libproxy/libproxy/blob/master/libproxy/proxy.h#L66

libproxy passes unversioned socks configuration to the application. The application needs to determine what to do with that information. libproxy **cannot** choose a version for an unversioned configuration.
