### ISSUE TITLE
LOOK OVER THIS BEFORE RELEASING 0.4.16: Addition of symbol versioning reportedly fixes libproxy crashes gjs applications when run outside GNOME

### ISSUE THREAD

**Issue by mcatanzaro** [libproxy/libproxy#82]
This is a follow-up to #81. The user who reported the issue in #81, in [this downstream bug](https://bugzilla.redhat.com/show_bug.cgi?id=1524507), reports that the problem was solved by commit 2fb80a007a1de4cf8603d7f686fdbaf46ded961a. I'm thinking that's probably not good. Could it indicate the symbol versioning has broken the module loader? I'd test carefully before releasing a new version of libproxy with that commit.

**Comment by mcatanzaro** [comment]
I've added "LOOK OVER THIS BEFORE RELEASING 0.4.16" to the title of this issue because I suspect a serious regression here.

**Comment by Vogtinator** [comment]
https://github.com/libproxy/libproxy/pull/112 fixes this.

**Comment by mcatanzaro** [comment]
> #112 fixes this.

Closing this, then.
