### ISSUE TITLE
How to compile Static library(.a) file from this source code?

### ISSUE THREAD

**Issue by StarNeit** [libproxy/libproxy#83]
I have just installed libproxy-dev on my Ubunt 16.04 with below command.

`sudo apt-get install libproxy-dev`

After install this library, only .so file is generated, but I hope to get .a file.
So, it means that I want to build static library file from this source code.

I really look forward any help or comment, Thank you.

**Comment by DimStar77** [comment]
A fully working static library is not possible, as libproxy dynamically loads its plugins (desktop detection, pacrunner, )
