### ISSUE TITLE
Unable to find required symbol

### ISSUE THREAD

**Issue by bigon** [libproxy/libproxy#88]
Hello,

It seems that libproxy with `_MM_DEBUG=1` always returns an "Unable to find required symbol" warning/error:

```
failed! : /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/modules/pacrunner_mozjs.so
	Unable to find required symbol: JS_DefineFunction
failed! : /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/modules/pacrunner_webkit.so
	Unable to find required symbol: JSObjectMakeFunctionWithCallback
```

The module seems to otherwise work fine

**Comment by DimStar77** [comment]
Yes, that is correct - we try first to see if the symbols are already in process before loading an external JS parser; so in case your calling app links webkit, we favor the webkit js parser
