### ISSUE TITLE
Problem to bypass the default proxy in Windows.

### ISSUE THREAD

**Issue by TrueXakeP** [libproxy/libproxy#96]
Hello.
I want to point out that the implementation of `w32reg_config_extension::get_ignore()` may be incomplete. In fact, it returns only `<local>` or empty string. The part that converts ";" in "," and returns the converted result, is missing.
https://github.com/libproxy/libproxy/blob/6cd4b831cb639caeac444b866290ed522e0e3a8f/libproxy/modules/config_w32reg.cpp#L158-L167

The problem is:
Using software with libproxy under the hood, I'm trying to connect to `127.0.0.1:8384` bypassing the system default proxy, which is `socks=192.168.37.1:9050`, but the system exclusions, which is `sync.tool;localhost;127.0.0.1;127.0.0.1:8384;192.168.37.77;<local>`, do not seem to work.

I'm using:
Windows 10 (1809)
[Syncthing-GTK](https://github.com/syncthing/syncthing-gtk) with gio library (can't find exact version)
[Syncthing](https://github.com/syncthing/syncthing)
My Internet Settings registry hive is:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"DisableCachingOfSSLPages"=dword:00000000
"IE5_UA_Backup_Flag"="5.0"
"PrivacyAdvanced"=dword:00000001
"SecureProtocols"=dword:00000a80
"CertificateRevocation"=dword:00000001
"User Agent"="Mozilla/4.0 (compatible; MSIE 8.0; Win32)"
"EnableNegotiate"=dword:00000001
"MigrateProxy"=dword:00000001
"ProxyEnable"=dword:00000001
"LockDatabase"=hex(b):6e,71,fa,0f,b4,52,d4,01
"ZonesSecurityUpgrade"=hex:79,81,2c,bf,28,5b,d4,01
"WarnonZoneCrossing"=dword:00000000
"ProxyServer"="socks=192.168.37.1:9050"
"ProxyOverride"="sync.tool;localhost;127.0.0.1;127.0.0.1:8384;192.168.37.77;<local>"
```
Also for reference:
Microsoft says that <local> in exclusions means simple hostname without a period and not an IP address. But in fact, IE forcibly bypasses the proxy when it connects to http://127.0.0.1

**Comment by DimStar77** [comment]
This was actually fixed with #133
